game/src/common/speed.rs

Add constant for background color (so the button's background disappears), and the duration of the game.

New speed panel

---

importer/src/main.rs

Parallelize importer

---

ezgui/examples/demo.rs
ezgui/src/canvas.rs
ezgui/src/event_ctx.rs
ezgui/src/lib.rs
ezgui/src/runner.rs
ezgui/src/tools/warper.rs
game/src/common/warp.rs
game/src/debug/mod.rs
game/src/edit/traffic_signals.rs
game/src/game.rs
game/src/pregame.rs
game/src/sandbox/mod.rs
game/src/sandbox/speed.rs
map_editor/src/main.rs

This PR is intended to resolve #58

Refactor event update loop

---

game/src/game.rs
game/src/pregame.rs

This PR is still WIP. Resolves #13.

Add title screen traffic

---

sim/src/make/generator.rs

per code review this is not actually a good idea

drop unneded todo

---

game/src/sandbox/dashboards/commuter.rs

Shows summary counts of building types within the selected block
**crowded**
With lots of building types, the label gets really long, stretching the widget horizontally. That's probably fine for now, but I don't like how it runs into the right edge of the widget. Is there a way to specify an inner margin on the outer commuter widget?

Commuter Patterns: building stats

---

sim/src/make/generator.rs

for now solely cars, next step would be having function deciding on trip mode based on distance and using it also here
note #206, this code may be buggy though at least sometimes transit traffic works
next potential step - some distribution of transit traffic over day

add transit traffic for #154

---

sim/src/make/generator.rs

use single trip mode selection function
(still extremely primitive, based on a distance)
border-to-border traffic is now more varied
rewrite TODOs

further work on #154 - better trip generator

---

docs/new_city.md

Adds short descriptions of the different guides

Improve New City Guide

---

convert_osm/src/osm_reader.rs
game/src/helpers.rs
game/src/layer/map.rs

also, add graveyards like cemeteries
some renaming/rearranging (media->culture), kindergarten moved to childcare from education, atm are no longer considered to be a bank (unsure about this one)

handle more OSM tags - especially POIs

---

Cargo.lock
headless/Cargo.toml
headless/src/main.rs
map_model/src/map.rs

@michaelkirk, @RestitutorOrbis, @goshawk22
This is just an initial demo. Once there's some specific use case for controlling the simulation from another language, the API can be fleshed out.

turn the headless runner into a demo of a JSON API, for #245

---

ezgui/src/backend_wasm.rs

just a little fixup to 1d46845d

Fix wasm compile

---

game/src/sandbox/gameplay/play_scenario.rs
sim/src/make/modifier.rs

new trips, then seeing the impact they'll have on the normal weekday
scenario. So how much externality would be caused by a bunch of new
trips if some building is built?
Demo showing the whole flow: https://youtu.be/adpED0KGQ7Q. Why do those
few trips at the beginning impact some later trips so much? Who knows.
Likely parking spots get gobbled up.
@michaelkirk

New tool to union two scenarios. One use case is manually defining some

---

book/src/api.md
data/MANIFEST.txt
game/src/info/intersection.rs
headless/examples/python_client.py
headless/src/main.rs
map_model/src/lib.rs
map_model/src/objects/traffic_signals.rs
map_model/src/objects/turn.rs
sim/src/analytics.rs
sim/src/events.rs
sim/src/mechanics/intersection.rs

Knowing how long people are waiting northbound vs southbound at a light is pretty important for auto-tuning traffic signals.
After this PR, I'll do the same thing for throughput.
@michaelkirk

Record delay through a traffic signal by direction, and expose through the API

---

.github/workflows/book.yml
map_model/src/map.rs
sim/src/cap.rs
sim/src/lib.rs
sim/src/mechanics/driving.rs
sim/src/mechanics/walking.rs
sim/src/sim.rs
sim/src/transit.rs
sim/src/trips.rs

@michaelkirk Next few steps on the congestion charging experiment

Enforce vehicle cap per hour

---

map_model/src/edits/mod.rs

apply()ing the new ones, ignore any common prefix between the two
command-lists.
@michaelkirk 
I tested manually with everything I could think of. The noticeable case for speedup is to bulk edit, select a bunch of roads, then attempt one of the driving->bus lane transformations.

Speed up apply_edits. Instead of undo()ing all current commands and then

---

book/src/case_studies/west_seattle.md
book/src/how_it_works.md
book/src/map/importing/rest.md
game/src/edit/traffic_signals/edits.rs
game/src/edit/traffic_signals/mod.rs
game/src/edit/traffic_signals/preview.rs
game/src/info/intersection.rs
game/src/render/intersection.rs
game/src/render/mod.rs
game/src/render/traffic_signal.rs
headless/examples/python_client.py
map_model/src/lib.rs
map_model/src/make/traffic_signals.rs
map_model/src/objects/traffic_signals.rs
sim/src/mechanics/intersection.rs
sim/src/sim.rs

controller terminology.
Holding off on touching PhaseType and all of the serialized
seattle_traffic_signals format, since this will all change in Kyle's PR
anyway.
@michaelkirk and @khuston

Rename Phase -> Stage, to be more in line with standard traffic signal

---

game/src/options.rs
game/src/sandbox/speed.rs

Followup to https://github.com/dabreegster/abstreet/pull/300#discussion_r479515546

timewarp restores last picked halt_limit

---

game/src/edit/traffic_signals/mod.rs
game/src/info/intersection.rs
game/src/render/mod.rs
game/src/render/traffic_signal.rs
game/src/render/turn.rs
game/src/sandbox/dashboards/traffic_signals.rs
headless/src/main.rs
map_model/src/edits/mod.rs
map_model/src/lib.rs
map_model/src/make/initial/mod.rs
map_model/src/make/mod.rs
map_model/src/make/traffic_signals.rs
map_model/src/map.rs
map_model/src/objects/traffic_signals.rs
map_model/src/objects/turn.rs
sim/src/analytics.rs
sim/src/events.rs
sim/src/mechanics/intersection.rs

https://github.com/dabreegster/abstreet/pull/302#discussion_r479571931
@khuston, let me know if this looks good and when to merge it. Thanks!

Mechanicallyish rename TurnGroup -> Movement for #197, as decided in

---

README.md
map_model/src/map.rs

fix broken dev guide link

---

book/src/dev/README.md

Add link to testing strategy in main dev doc

---

Cargo.lock
sim/src/make/activity_model.rs
widgetry/Cargo.toml
widgetry/src/lib.rs
widgetry/src/runner.rs

Sorry, a couple things I hadn't pushed up for #320 yet.
The workflow I'm used to is to respond to PR feedback line by line as I work on it, then re-tag "Please take another look..." for review when I'm finished. This is potentially confusing, so in the future I'll try to address everything before making confusing statements like "done". 😓 
Also took the opportunity to shave off a little more log spam.

log cleanups

---

game/src/sandbox/dashboards/commuter.rs
importer/src/berlin.rs
map_model/src/make/buildings.rs
map_model/src/objects/building.rs
sim/src/make/activity_model.rs

Currently this is only used by the ProletariatRobot demand model.
/cc @matkoniecz

estimate worker capacity of commercial buildings similar to residential capacity

---

game/src/common/colors.rs
widgetry/examples/demo.rs
widgetry/src/backend_glow_native.rs
widgetry/src/color.rs
widgetry/src/geom.rs
widgetry/src/lib.rs
widgetry/src/svg.rs

Based on #333, so merge that first.

rename `FancyColor` to `Fill`, and improve ergonomics with `Into`

---

Cargo.lock
game/Cargo.toml
game/src/edit/select.rs
game/src/edit/traffic_signals/mod.rs
game/src/edit/traffic_signals/offsets.rs
map_model/src/map.rs
sim/src/make/scenario.rs

This is a second attempt at a UI for changing the offset between multiple traffic signals. Could definitely use further improvement, but this is much better than dumping a bunch of sliders in a panel.
Design notes from Slack:
- Every intersection has a single offset parameter, some number of seconds relative to some master clock. There's just one offset per intersection; it's not per direction of movement or anything like that. When editing a single intersection, it could be useful to show the value, although in isolation it's not too meaningful.
- If you pick two intersections, it's meaningful to look at the relative offset between the two. If i1 has offset of 5s and i2 has offset of 15s, then the i1->i2 offset is 10s
- If you have a bunch of signals along a big road and you want to get …

UI to tune signal offsets

---

game/src/common/mod.rs
game/src/debug/polygons.rs
game/src/sandbox/dashboards/parking_overhead.rs
game/src/sandbox/dashboards/summaries.rs
game/src/sandbox/dashboards/table.rs
game/src/sandbox/dashboards/trip_table.rs
widgetry/src/assets.rs
widgetry/src/drawing.rs
widgetry/src/text.rs
widgetry/src/widgets/button.rs
widgetry/src/widgets/compare_times.rs
widgetry/src/widgets/fan_chart.rs
widgetry/src/widgets/line_plot.rs
widgetry/src/widgets/menu.rs
widgetry/src/widgets/scatter_plot.rs

Just a little widgetry cleanup

Coalesce render flavors

---

map_model/src/make/traffic_signals.rs
map_model/src/objects/traffic_signals.rs

The new docs look good! Just fixed a couple little typos I encountered.

fix doc typos

---

game/index.html
widgetry_demo/index.html

I didn't spend too much time on this, but I think it will help assure people that something is happening. Currently it kind of feels broken.

loading screen

---

widgetry/src/backend_glow.rs

We're spending a lot of time loading textures in wasm debug builds. It's a bit of a false alarm in that non-wasm builds and non-debug builds don't seem to be much affected by it, but it can't hurt.
**before: 2.0s**
**after 0.36s**
It's significantly faster, but still surprisingly slow (360ms in debug). Further improvements could be done by operating on the bytes directly, but the windowing logic we get from GenericImageView is annoying enough to implement that it didn't seem worth it for now.

speed up texture loading - minimize vector alloc

---

game/src/devtools/fifteen_min/mod.rs

follows prior art for implementation. need support to determine real content we want to share.

add about button to hovering panel for 15 min neighborhood sub-app

---

game/src/devtools/fifteen_min/mod.rs

Switch neighborhoods in the 15m neighborhood view via the "City Picker" widget.

---

game/src/devtools/fifteen_min/mod.rs

The event I was previously looking for was too low level.

dont switch buildings while panning

---

game/src/common/mod.rs
game/src/edit/lanes.rs
game/src/edit/stop_signs.rs
game/src/edit/traffic_signals/edits.rs
game/src/sandbox/uber_turns.rs

This is closer to a callback style, which might be more familiar to
people coming from other frameworks.
It's a pretty mechanical refactor now, but the hope is that looking at a
bunch of on_mouseover() functions will reveal further refactors more
easily than a bunch of monolithic event() functions.
I don't think every State fits this pattern; things like SandboxMode
need to carefully orchestrate the order of things. Make simple things
easy and hard things possible.
@michaelkirk, @gedkott : Any opinion on this? There are many more places it could be applied, but I don't want to spend the time before being more convinced this is helpful.

Experiment with separating concerns in some simple States.

---

widgetry/src/backend_glow_native.rs

Introduces a couple of fallbacks aimed at addressing https://github.com/dabreegster/abstreet/pull/396
@gedkott - would you please try building this branch and let me know if the app launches for you?
And also, whether it works or not, can you also get me your log output (maybe as a [gist](https://gist.github.com).

More robust OpenGL setup

---

popdat/src/activities.rs
popdat/src/distribute_people.rs
popdat/src/import_census.rs
popdat/src/lib.rs
popdat/src/make_person.rs

- adapt the Berlin logic for disaggregating people to buildings
- start some person -> activity -> schedule mappings
- clean up all the unused var warnings
@michaelkirk

Get more pieces of popdat working:

---

geom/src/bounds.rs
geom/src/pt.rs
map_gui/src/colors.rs
widgetry/src/color.rs
widgetry/src/geom.rs
widgetry/src/widgets/button.rs
widgetry/src/widgets/mod.rs

A small handful of little changes I separated from the button work - no changes in behavior.

little changes

---

fifteen_min/src/find_home.rs
fifteen_min/src/viewer.rs
game/src/challenges/cutscene.rs
map_gui/src/tools/city_picker.rs
osm_viewer/src/viewer.rs
santa/src/title.rs
widgetry/src/style/mod.rs
widgetry/src/widgets/button.rs
widgetry/src/widgets/checkbox.rs
widgetry_demo/src/lib.rs

Sorry, I missed some calls to Btn::text_bg1, and broke some of the secondary bins in 11ffef571

more button progress and fixups

---

game/src/sandbox/gameplay/tutorial.rs
game/src/sandbox/uber_turns.rs
map_gui/src/tools/turn_explorer.rs
widgetry/src/style/buttons.rs
widgetry/src/widgets/table.rs

Button fixes: wrong pager icon in tutorial, clobbered hotkeys in tutorial

---

game/src/devtools/story.rs
game/src/info/person.rs
map_gui/src/colors.rs
map_gui/src/tools/minimap.rs
santa/src/title.rs
widgetry/src/style/mod.rs

Remove the last traces of the old orange hovering color.

---

game/src/lib.rs

https://github.com/cyipt/actdev/issues/44
To try this out:
1) Go somewhere on OSM, like https://www.openstreetmap.org/#map=17/47.64118/-122.31143
2) Copy that parameter and run `cargo run -- --dev --cam=17/47.64118/-122.31143`
For me, OSM is:
And abst:
I circled the same spots on both. As you can see, this matches up _pretty_ well, but abst is always a bit too big. I can't figure out why. Of course the abst window height is a little more generous, without OSM's top header, but I'd expect things to at least line up horizontally.
@michaelkirk This might be good enough for the actdev integration (browse a normal slippy web map, then press a button to jump to the same point in abst), but I figured you might spot the likely silly problem with my math.

Apply an initial camera zoom when passing the --cam param. For

---

README.md
importer/src/bin/generate_houses.rs
sim/src/mechanics/intersection.rs

This shouldn't have any behavioral change.
@BruceBrown

Cache the list of nearby intersections to wake up for uber-turns. #497

---

game/src/info/mod.rs
game/src/layer/mod.rs
map_gui/src/tools/city_picker.rs
widgetry/src/style/buttons.rs
widgetry/src/style/mod.rs
widgetry_demo/src/lib.rs

This gets us closer to Yuwen's design.

Clean up hotkey buttons and colored text buttons

---

map_gui/src/colors.rs
widgetry/src/assets.rs
widgetry/src/event_ctx.rs
widgetry/src/runner.rs
widgetry/src/style/mod.rs
widgetry/src/text.rs

This required moving (a copy of) Style to Assets.

Text gets default color from Style

---

game/src/sandbox/gameplay/freeform.rs
widgetry/src/widgets/table.rs

Attempts to addresses this feedback:  https://github.com/a-b-street/abstreet/pull/571#issuecomment-802972514

scenario picker

---

game/src/info/building.rs
game/src/info/bus.rs
game/src/info/debug.rs
game/src/info/intersection.rs
game/src/info/lane.rs
game/src/info/mod.rs
game/src/info/parking_lot.rs
game/src/info/person.rs
widgetry/src/lib.rs
widgetry/src/widgets/mod.rs
widgetry/src/widgets/tabs.rs

https://user-images.githubusercontent.com/217057/111885651-6058fe00-8986-11eb-8204-8033f7dfbdf2.mp4
Because the existing InfoPanel design is pretty coupled to it's functionality, I decided not to use the new TabController, and instead copied around some code to mimic the style.

new tab styles for info panels

---

game/src/sandbox/gameplay/tutorial.rs

- Fix a typo
- Draw a star on the car that the player is supposed to follow
- Move the message panel to the left when pointing to the minimap and
layers
- Add button icons to the message box to really emphasize what we're
pointing to
A few people have reported issues figuring out which car to follow, especially when their window size messes up.
So why don't we just draw a star on that car for the entire tutorial step?
Happy to adjust size/color/icon.
We kind of fail at pointing to the "layers" button, because the message box overlaps the minimap:
So let's move that message box over, and also add the layer icon to the message box.
Every time we point to a button, we can include that icon to really emphasize it:
Yuwen raised the idea of changing the follow car challenge to not require …

Tutorial fixes after a UX study:

---

game/src/edit/roads.rs
widgetry/src/widgets/mod.rs

rebased and re-opened #628, now targeting master

road cards design tweaks

---

geom/src/duration.rs
widgetry/src/widgets/spinner.rs

Let the UI polish continue!
This style was chosen from a vote in Slack. Happy to adjust if there's something nicer.

Change how durations are printed

---

game/src/edit/roads.rs

I took a stab at building more sensible default behavior. I am very new to rust so sorry if it's not very idiomatic, I figure the only way to learn is to start writing and get critiqued!
This works pretty well for streets regardless of the side of the street is Fwd and Back (it looks at the number of Fwd and Back lanes, defaults to Fwd unless there are too many Fwd in which case will make the direction Back). Currently it looks at all of the lanes to determine this balance (I could also see the argument to only look at drivable lanes to determine the balance of Fwd and Back).
For other types of lanes, there are a lot of edge cases as I looked around the map. If for example there is a parked car lane on the side where a bike lane gets added, the bike lane will be sandwiched between the …

Add default behavior for driving, non driving and sidewalks

---

widgetry/src/widgets/panel.rs

Addressing this comment: https://github.com/a-b-street/abstreet/pull/647#discussion_r632879121
After doing some profiling and also experimenting with commenting out portions of code, I came to the conclusion that the performance degradation brought up in #647 was due to how widgetry recomputes the flexbox of a panel each time it processes a scroll event (which happens many times per second).
So the regression wasn't really due to any categorically new behavior, but rather just that scrolling panels gets more expensive the more complex the layout is.
The solution proposed here is to cache the flexbox, and use the cached flexbox when scrolling rather than recomputing anew.
Here's a snippet of the profiler while scrolling up and down in the "travel times" screen before vs after these …

PERF: don't recompute flexbox when scrolling

---

data/MANIFEST.json
game/src/challenges/prebake.rs
sim/src/sim/mod.rs
tests/goldenfiles/prebaked_summaries.json

This is an interim option until we decide whether this setting belongs
on the map, the scenario, or something else.
I'm regenerating data now, will post the graphs.

Hardcode infinite parking option for a few maps. #688

---

web/Makefile
web/README.md

Following up on https://github.com/a-b-street/abstreet/pull/702#discussion_r671439319

rebuild wasm when rust sources change

---

widgetry/src/canvas.rs
widgetry/src/event.rs
widgetry/src/input.rs
widgetry/src/runner.rs

I minimal double-click to zoom implementation on canvas - there are some caveats in the comments. Give it a whirl and let me know what you think.
https://user-images.githubusercontent.com/217057/130303654-651f4509-7da5-4d15-b4d8-db106513c9b1.mov

canvas: double click to zoom

---

game/src/ungap/layers.rs

**before** 
Some of the legend items were notably shorter ("minor street", "trail", and the inner steep streets)
**after**

Uniform heights for legend items

---

game/src/edit/roads.rs

The goal of this PR is to more clearly show which controls correspond to an individual lane vs the entire road.
1. "drill down" - so attributes applying to the entire road are up top,
while attributes applying to only a single lane are below.
2. use "tab" metaphor to treat each lane as a tab, showing the lane
attributes beneath the "active" lane-tab. 
https://user-images.githubusercontent.com/217057/130745934-a4f128d8-bbad-4605-aff6-213204219f1a.mp4
Note 1: the video shows some strange lane swapping, but I believe that's (#731 reproduced against master), not something new to this PR.
Note 2: I was hoping to get a little bit closer to @muzlee1113's "floating" designs. Unfortunately I couldn't find the original designs in Figma 😓

road editor style changes

---

game/src/challenges/cutscene.rs
game/src/common/waypoints.rs
game/src/edit/mod.rs
game/src/edit/traffic_signals/mod.rs
game/src/pregame/mod.rs
widgetry/src/event_ctx.rs
widgetry/src/screen_geom.rs
widgetry/src/style/button_style.rs
widgetry/src/widgets/button.rs
widgetry/src/widgets/drag_drop.rs
widgetry/src/widgets/image.rs

Several small changes - probably easiest to understand in the individual commits.
**before**
**after**
https://user-images.githubusercontent.com/217057/132773537-d0fddc9a-76d5-410f-a34b-37093ed88284.mp4

UI touchups for the route drag/drop

---

apps/ltn/src/connectivity.rs
widgetry/src/drawing.rs
widgetry/src/tools/lasso.rs
widgetry/src/tools/mod.rs

Often I know what I want the cells of an LTN to look like, and adding individual filters is too slow. Harness the inner fruit ninja instead...

Quickly sketch desired LTN cells freehand!

---

apps/ltn/src/rat_runs.rs

The purpose of the rat-run viewer is to show all possible ways that a driver might cut through a neighborhood. Previously, the tool showed some things that were neither rat-runs nor a likely route that would happen in reality. If the original rat-run is
and you add a filter, you previously got:
which is silly. The optimal path is to technically loop around and use the main road. But that's not what this tab is trying to show.
Filter out any path that leaves the neighborhood. That particular rat-run (from the same A and B position) disappears entirely.
```
// Some paths dip out of the neighborhood. Even though the entrance and exit is in the same
// cell, the optimal path is to use a boundary road. Filter those out.
paths.retain(|path| {
path.get_steps().iter().all(|step| {
if let …
```

When calculating rat-runs, force pathfinding to stay inside the neighborood. #839

---

apps/game/src/sandbox/speed.rs
apps/game/src/sandbox/time_warp.rs
apps/game/src/ungap/mod.rs
apps/ltn/src/browse.rs
apps/ltn/src/common/mod.rs
apps/ltn/src/connectivity.rs
apps/ltn/src/impact/ui.rs
apps/ltn/src/lib.rs
apps/ltn/src/per_neighborhood.rs
apps/ltn/src/rat_run_viewer.rs
apps/ltn/src/route_planner.rs
apps/ltn/src/select_boundary.rs
map_gui/src/colors.rs
map_gui/src/tools/city_picker.rs
widgetry/src/event_ctx.rs
widgetry/src/lib.rs
widgetry/src/widgets/mod.rs
widgetry/src/widgets/panel.rs
widgetry_demo/src/lib.rs

Based on Cindy's initial Figma designs:
Start to tease apart the LTN panels into a top bar and a left panel.
https://user-images.githubusercontent.com/1664407/157208781-efad6b7e-6b91-4b4c-8425-4b2c72760e7e.mp4

Rearrange LTN panels

---

apps/ltn/src/connectivity.rs
apps/ltn/src/per_neighborhood.rs
apps/ltn/src/rat_run_viewer.rs

Placing filters requires the user to think about two things at the same time: connectivity changes and how drivers might detour. Currently they have to flip between two tabs to see this. But... why? Let's just combine them:
https://user-images.githubusercontent.com/1664407/158071694-54ef25f2-88b5-4c73-9b5d-7ecee62140d7.mp4
You can watch me play whack-a-mole, and the dark red moving around intuitively tells me the detour. Then at the end, I reverse my mess and find the simpler approach.
The rat-runs tab is now simplified -- it just lets you browse individual paths, in case you're not convinced by the heatmap:
https://user-images.githubusercontent.com/1664407/158071787-492666ce-dcbe-4e69-93ec-0dff634c8bc5.mp4
Some possible next steps:
- Put the "10/30 streets allow through-traffic" on this …

Show the rat-run heatmap on the connectivity tab.

---

Cargo.lock
Cargo.toml
apps/game/Cargo.toml
apps/ltn/Cargo.toml
cli/Cargo.toml
geom/Cargo.toml
importer/Cargo.toml
popdat/Cargo.toml

No big changes here.
I often update ABStreet as a sanity check for proposed changes to georust, and figured I might as well submit that update.

update deps -> geo: 0.20.1, geo-types: 0.7.4, polylabel: 2.4.1

---

map_gui/src/render/intersection.rs
sim/src/recorder.rs

Very excited about this project. Refactoring a bit as I familiarize myself with the code. I will keep such refactorings to myself in the future if this PR is rejected.

Opinionated refactoring of intersection.rs and recorder.rs

---

Cargo.lock
Cargo.toml
apps/game/Cargo.toml
apps/ltn/Cargo.toml
apps/ltn/src/draw_cells.rs
apps/ltn/src/export.rs
cli/Cargo.toml
cli/src/clip_osm.rs
geom/Cargo.toml
geom/src/conversions.rs
geom/src/find_closest.rs
geom/src/gps.rs
geom/src/polygon.rs
geom/src/polyline.rs
geom/src/pt.rs
geom/src/ring.rs
importer/Cargo.toml
importer/src/pick_geofabrik.rs
popdat/Cargo.toml
popdat/src/distribute_people.rs
popdat/src/import_census.rs
popdat/src/lib.rs

You can omit the second commit if you'd prefer to remain explicit about the geo geometries storing f64 coordinates.

update geo to 0.22.0

---

apps/ltn/src/shortcuts.rs

Previously we were just banning movement along the perimeter road, but
that doesn't achieve the intended effect.
Before:
and even more creatively
After:
There's more work still to deal with `access=private`, but that needs more thought. Will followup with another PR.

Shortcuts calculated must stay totally within the neighbourhood. #968

---

Cargo.lock
Cargo.toml
apps/fifteen_min/Cargo.toml
apps/game/Cargo.toml
apps/ltn/Cargo.toml
apps/ltn/src/impact/ui.rs
geom/Cargo.toml
geom/src/bounds.rs
geom/src/polyline.rs
geom/src/pt.rs
headless/Cargo.toml
importer/Cargo.toml
map_gui/Cargo.toml
map_model/Cargo.toml
popdat/Cargo.toml
widgetry/Cargo.toml

The new [geojson::FeatureWriter](https://docs.rs/geojson/latest/geojson/struct.FeatureWriter.html) API allows sharing some code between the CSV and GeoJSON outputs.
Let me know what you think!

update geojson, contours. Use new FeatureWriter API

---

apps/ltn/src/shortcuts.rs

There was a very insidious little bug lurking, and someone at a Bristol workshop caught it! Why isn't there a shortcut up Newham Road here?
The answer is in an old assumption made about filtering out "trivial" shortcuts where the main road at each end isn't "different." When the endpoints were at a place where the road name changes, previously we just bailed out. This PR fixes that. Now we're good:
The problem could be seen even more clearly in a simple case before:
There are no shortcuts on one road, just because E Montlake Pl becomes 24th Ave. Now it's fixed:

Consider shortcuts between corners where a main road changes names.

---

geom/src/line.rs
geom/src/polyline.rs
geom/src/ring.rs

This is a simple first step towards the goal described in the issue.
Closes #1005 and #1051. I tested a few end-to-end things in this repo.

Stop crashing for duplicate adjacent points. #1061

---

data/MANIFEST.json
importer/actdev_site.sh
importer/src/map_config.rs

Fixes #1102.
I need to regenerate the few dozen affected maps; will do so later today, possibly along with another change.

Remove procedurally generated buildings from some UK maps

---

apps/game/src/sandbox/dashboards/trip_table.rs
widgetry_demo/src/lib.rs

This piece of code adds a button underneath the trip tables overlay to export it into a csv file for analysis of trips.

Added a button that exports the trip table to a CSV file.
