a-b-street/abstreet

- popdat/src/psrc.rs
I got the following error when running `cs2cs`
```
cannot instantiate source coordinate system
program abnormally terminated
```
[The "+init=esri:1234" syntax is deprecated](https://pyproj4.github.io/pyproj/dev/gotchas.html#init-auth-auth-code-should-be-replaced-with-auth-auth-code). This just uses
the new "esri:1234" syntax, which runs on Mac OSx.
> Fix cs2cs call when generating popdat.bin

- ezgui/src/canvas.rs
- ezgui/src/managed.rs
- game/src/common/mod.rs
- game/src/options.rs
Resolve #11
I created two bounding boxes, an inner bounding box in screen space and a map bounding box in map space. The presence of the cursor within the inner bounding box is used to determine whether or not the cursor is at the edge of the screen and the presence of the cursor within the map bounding box is used to determine whether further panning would bring the user out of the map. I've also implemented a setting to disable panning if the user doesn't like it.
Once, it's determined that panning should take place, I calculate the centre of the screen and then calculate the displacement vector from the cursor position to the centre of the screen. Then, I calculate the magnitude of the displacement and use it to convert the displacement vector to a unit vector. The resulting unit …
> Auto-pan map when cursor is at edge of screen

- game/src/sandbox/speed.rs
- geom/src/time.rs
This allows me to quickly and precisely jump to the same time every
time.
> Round time to 10 minutes in jump to dialog

- game/src/common/city_picker.rs
Thought I'd try to fix the issue I opened (#101 ).
First, the zoom was not using the scale factor, so the city picker window was too large (bigger than the screen) for larger scale factors (e.g. 2.0 on my Mac).  Adding the scale factor to the calculation of `zoom` fixes this.
But, it appears that `regions` shouldn't be scaled according to the scale factor. (A comment says it's in "untranslated screen-space".)  In any case, using the zoom without the scale factor for the regions, while using the zoom with the scale factor for the batch, appears to fix this issue.  I tested it using different scale factors.
Since I don't really know what I'm doing, there may be a more sensible way to name or structure these calculations.  Let me know.
> fix math in city picker to use scale factor

- game/src/helpers.rs
neither Bronowice, nor Nowa Huta are included
Entire one should included airport terminal on West ( https://www.openstreetmap.org/?mlat=50.0701&mlon=19.7960#map=12/50.0701/19.7960 )
and reach main steelwork entrance on East ( https://www.openstreetmap.org/?mlat=50.0787&mlon=20.0682#map=12/50.0787/20.0682 )
Current area is fitting (capable of running on my laptop) and good one if one wants to play solely with city center, just name is misleading.
> it is just city center, not entire one

- game/src/sandbox/dashboards/commuter.rs
Commuter patterns offered two different styles to visualize the
source/destination of travellers.
1. Arrows points to the source/destination
2. Heat map showing relative density of the source/destination
The arrow mode was visually cluttered and yet didn't communicate as much
info as the heatmap, so we're getting rid of it.
**before**
**after**
> Commuter Patterns: remove arrow overlay mode

- game/src/sandbox/dashboards/commuter.rs
Before:
After:
Diff:
The ColorScale is based on 0..max_value, so it seems confusing to label the scale from 0..total_count.
It was nice to have the total count though, so I added another label.
WDYT @dabreegster?
> Commuter Pattern: label heatmap scale accruately (by max, not total)

- game/src/sandbox/dashboards/commuter.rs
In commuter patterns, now that you can click-to-lock onto a particular region, it seems a little strange that nothing changed when you hovered over other blocks. Now, after clicking a block, we show the count of trips to/from the hovered region (based on current filters).
Overview showing first the existing hover behavior without locking, then after locking, the new "hover" behavior:
Currently, I'm showing the label for zero counts too - it seems helpful. WDYT?
The number is hard to read over blocks with no traffic. I could add some kind of mask to the entire block under hover, but I thought it was useful to keep the original heatmap tone visible.
A couple options:
- We could just not show the label at all for blocks with a zero count, but I personally think it's helpful information.
- I …
> Commuter Patterns: Show secondary stats for commute on hover

- game/src/sandbox/dashboards/commuter.rs
- geom/src/polyline.rs
Fixes #215 
A substantial portion of traffic has an origin/destination off the map.
We were correctly tracking all this data, attributing it to a
"block" the size of the border "intersection"; However, the design
didn't accommodate the small "size" of the border intersections:
**before**
1. it was too small to meaningfully reason about the heatmap visualization
2. it was too small of a "hit" area for clicking and hovering
3. when in the "locked" mode, the hover text overlay was illegible.
**after**
Now we draw a larger arrow, representing the inward/outward/both-ways
direction of traffic which makes it easier to reason about the heatmap
color and accommodates an adequate hit area.
And the hover text is now printed over a white pill to maintain
legibility.
>  Commuter Patterns: Larger shapes for border intersections

- ezgui/examples/demo.rs
- ezgui/src/widgets/checkbox.rs
- game/src/common/heatmap.rs
- game/src/debug/mod.rs
- game/src/devtools/destinations.rs
- game/src/devtools/mapping.rs
- game/src/info/mod.rs
- game/src/layer/pandemic.rs
- game/src/layer/parking.rs
- game/src/layer/population.rs
- game/src/layer/traffic.rs
- game/src/layer/transit.rs
- game/src/options.rs
- game/src/sandbox/dashboards/commuter.rs
- game/src/sandbox/dashboards/parking_overhead.rs
- game/src/sandbox/dashboards/trip_table.rs
- game/src/sandbox/speed.rs
partial revert of 90bb4ac0
In many ways switches and checkboxes seem interchangeable, but in certain
contexts one may be more appropriate.
For an overview that I mostly agree with:
https://uxplanet.org/checkbox-vs-toggle-switch-7fc6e83f10b8
**before**
**after**
Most things continue to use switches - especially those which produce instance feedback without a "submit" step.
However, I feel like the switch labels are too large. That didn't change with this PR, but would you be interested in a followup PR which makes the switch text size comparable to what you see on the checkboxes?
> revert some switches back to checkboxes

- ezgui/src/backend_wasm.rs
- ezgui/src/geom.rs
- game/src/edit/mod.rs
- game/src/edit/new_traffic_signals.rs
- game/src/edit/stop_signs.rs
- game/src/edit/traffic_signals.rs
- game/src/sandbox/mod.rs
- game/src/sandbox/uber_turns.rs
Problem: Traffic signal configuration affects other intersections nearby. In this example downtown, there's a trio that cause gridlock, because by default, they're not timed relative to each other at all. Trying to adjust this manually sucks:
One idea is to edit all 3 intersections at the same time. After somehow selecting all 3 of them, you could initially force them to have the same number of phases (with the same duration). Then you can jump between phases, and see the normal icons for editing individual turns, but for all 3 intersections at once. Here's a small first step towards this:
The `TrafficSignalEditor` code is quite complex, so my plan is to rewrite it in this new copy, simplifying pieces as I go. The single intersection case can then just use the new code.
@michaelkirk
> Multi-intersection traffic signal editor

- Cargo.lock
- ezgui/Cargo.toml
Addresses an upstream winit bug, you can see the fix here: https://github.com/rust-windowing/winit/compare/master...michaelkirk:mkirk/fix-stdweb-dpi?expand=1
@dabreegster - can you do a sanity check to make sure this looks good on your device, then I'll open an upstream PR with winit.
**before**
You can see how things look good initially, but then gets wonky because the logical size, which is set in css style, gets clobbered when setting the cursor style.
**after**
Not sure if you'd want to merge this reference to my winit fork or prefer to wait 'til a fix is upstreamed. Note it also includes a few unreleased winit commits from HEAD.
> Fix HiDPI screens for wasm

- Cargo.lock
- ezgui/Cargo.toml
- game/src/challenges.rs
- game/src/cutscene.rs
- game/src/devtools/mapping.rs
- game/src/devtools/mod.rs
- game/src/edit/lanes.rs
- game/src/edit/mod.rs
- game/src/edit/stop_signs.rs
- game/src/edit/traffic_signals/edits.rs
- game/src/game.rs
- game/src/info/mod.rs
- game/src/pregame.rs
- game/src/sandbox/gameplay/fix_traffic_signals.rs
- game/src/sandbox/gameplay/freeform.rs
- game/src/sandbox/gameplay/mod.rs
- game/src/sandbox/gameplay/play_scenario.rs
- game/src/sandbox/gameplay/tutorial.rs
- game/src/sandbox/mod.rs
- game/src/sandbox/speed.rs
combining primitive transitions into sequences.
Brief context on the state/transition system: The game crate is
organized as a stack of states, with the topmost one being active.
Transitions manipulate this stack. For example, the stack might look
like: [main menu, sandbox mode, edit mode, traffic signal editor, signal
picker]
@michaelkirk
> Refactor the Transition enum, collapsing enum variants that were

- Cargo.lock
- Cargo.toml
- ezgui/Cargo.toml
85ad194d introduced a patched winit.
In the glium build, we were pulling in a second version of winit (via
glutin). This caused conflicts between the data types, breaking the
build.
Apparently the proper way to specify a patch like this, usable by
transitive dependencies, is via cargo's "patch" specifiers
> Fix glium build, which was broken with: 85ad194d

- game/src/sandbox/gameplay/freeform.rs
- sim/src/sim.rs
- sim/src/trips.rs
trips as a Scenario to later re-run. This is useful for quickly defining
"test cases" for development, and it's a start to a UI for letting
players specify (and eventually share) traffic patterns they define.
@michaelkirk
> In traffic=none mode, allow recording (most of) the manually specified

- game/src/edit/traffic_signals/mod.rs
- sim/src/mechanics/intersection.rs
@michaelkirk: The offset between two traffic signals lets you create "green wave", delaying one signal relative to another. This is a very primitive first attempt at editing offsets:
It has many problems, but it's a start. I don't yet have any clear ideas for something better. Ideally there'd be a way to see the best-case time (distance / speed) between any two signals for a certain mode (green wave for pedestrians?!). Offset as shown now is absolute, but really is more meaningful to display relative to other signals. And offset, I think, is directional -- you could turn a light green right as westbound traffic hits an intersection, but then doing the same thing as the eastbound traffic hits the other is... tricky.
Some potential ideas for next steps: …
> Prototype offset editing

- ezgui/src/shaders/fragment_140.glsl
- ezgui/src/shaders/vertex_140.glsl
Without this change, the screen was blank when using the glow backend on macos.
Some debugging traced it down to the shader attribute configuration.
@dabreegster suggested trying to declare a newer version of the shader
language which supports the syntax for explicit attribute layout, which
fixed it.
Tested both glow and glium backends for both the game and the ezgui example on my macos.
@dabreegster can you test on your device before merging?
> Fix glow backend on mac

- game/src/edit/bulk.rs
- game/src/edit/lanes.rs
- game/src/edit/mod.rs
- game/src/edit/validate.rs
- game/src/edit/zones.rs
- game/src/layer/map.rs
- game/src/sandbox/gameplay/mod.rs
- game/src/sandbox/gameplay/tutorial.rs
- map_model/src/edits/mod.rs
- map_model/src/edits/perma.rs
- map_model/src/lib.rs
- map_model/src/make/initial/lane_specs.rs
- map_model/src/objects/intersection.rs
#113 and #234 are both partly caused by a tension between two things:
1) The edit commands apply to an individual lane -- some lane's type is changed, another is reversed
2) When we serialize edits, we "compress" all of the commands, so that a bunch of changes to one lane aren't all captured. This compression fiddles with the order of commands.
Upon loading the saved edits with the compressed commands, it crashes. This PR takes a very different strategy -- just capture the entire state of a road in an edit command. It's actually pretty simple, and the original state can even be determined purely from the OSM tags -- lane types, lane directions, speed limit, and access restrictions.
I've tested various edit->save->load scenarios and believe this works.
The big TODO, for a followup PR, is …
> Represent edits to a road in a more robust way

- game/src/edit/mod.rs
- game/src/info/mod.rs
- game/src/sandbox/speed.rs
- sim/src/mechanics/intersection.rs
While playing ABStreet, I often want to "go to the worst spot" and investigate.  Until there's substantial traffic, it can be hard to find the 'worst spot'. I think that's why the "jump to delay" feature exists. It super handy.
However, a lesser delay can be jumped to sooner, especially on some of the less trafficy maps (e.g. montlake),  where a 5 minute delay never occurs.
> Make the "jump to delay" duration configurable.

- game/src/sandbox/speed.rs
I stand corrected! Skipping drawing can make a substantial difference (when zoomed in, in particular).
> show sim time and speed

- game/src/info/intersection.rs
- game/src/info/trip.rs
- widgetry/src/text.rs
> preserve whitespace

- game/src/sandbox/speed.rs
There's a couple places in the app which "jiggle", which I'd like to fix.
One of them is the warp screen:
A couple tools at our disposal: monospaced fonts and format padding. But a couple of issues that might not make the current proposal a net win, as is:
Firstly, as far as I can tell, it's not possible to have different fonts within a line. 
I'm looking for something like https://developer.apple.com/documentation/foundation/nsattributedstring, which allows you to specify different fonts for different sections of a string. Is there an existing way to achieve something like this in TUIFFKAEZG?
Otherwise, it doesn't look great to just use monospace font for the entire text:
Secondly, until https://github.com/RazrFalcon/resvg/issues/317 is addressed, trailing padding in text is effectively …
> WIP: avoid jiggle in warp Panel

- convert_osm/src/parking.rs
- data/MANIFEST.txt
- game/src/debug/mod.rs
- game/src/devtools/mapping.rs
- game/src/layer/map.rs
- game/src/render/intersection.rs
- game/src/render/lane.rs
- game/src/render/pedestrian.rs
- map_model/src/edits/mod.rs
- map_model/src/make/initial/geometry.rs
- map_model/src/make/initial/lane_specs.rs
- map_model/src/make/initial/mod.rs
- map_model/src/make/mod.rs
- map_model/src/make/walking_turns.rs
- map_model/src/map.rs
- map_model/src/objects/turn.rs
- map_model/src/pathfind/uber_turns.rs
- map_model/src/raw.rs
- sim/src/mechanics/walking.rs
My first attempt at handling left-hand driving was to take all of the code that shifts a road center line left/right and just sort of invert it. That actually did work, but it was extremely confusing and was an API change that percolated everywhere. Now that we have `lanes_ltr` and not `children_fwd/back`, rip out the old hack and handle things in just one smaller, unit tested place.
@michaelkirk
> Revamp the initial support for driving on the left

- Cargo.lock
- Cargo.toml
- widgetry/src/event.rs
horizontal scroll in abstreet moves content in the opposite direction vs other apps on macos. 
I'm not sure if the change is really this simple. It fixes things for me on macos, which has ubiquitous [natural scrolling], but maybe it breaks it for others.
Does this break things for you @dabreegster?
[1] Some terms:
> [Reverse Scrolling]: Swipe fingers up on trackpad, magic mouse, scroll-wheel, content goes down, scrollbar goes up.
> [Natural Scrolling]: Swipe fingers up on trackpad, magic mouse, scroll-wheel, content goes up, scrollbar goes down.
> macos fix: flip h-scroll to conventional direction

- book/src/trafficsim/live_edits.md
- game/src/debug/mod.rs
- game/src/edit/mod.rs
- game/src/edit/stop_signs.rs
- game/src/layer/map.rs
- game/src/options.rs
- game/src/sandbox/gameplay/mod.rs
- map_model/src/edits/mod.rs
- sim/src/lib.rs
- sim/src/make/load.rs
- sim/src/mechanics/driving.rs
- sim/src/mechanics/intersection.rs
- sim/src/mechanics/parking.rs
- sim/src/mechanics/walking.rs
- sim/src/router.rs
- sim/src/sim.rs
- sim/src/trips.rs
The goal is to not reset the simulation to midnight after making map edits. This has been requested by a few of the machine learning groups working through the API, and has been a long-time UX / instant gameplay feedback issue.
V1 of this change finds trips affected by edits and deals with them in the simplest way that doesn't crash the game -- usually just aborting the trip. Even with this, there are lots of crashes left. There are also changes to the tutorial, VIP challenge, and UI (explaining to players how their edits affect the live world) that haven't been thought through yet. So for now, hide everything behind a `--live_map_edits` flag.
> Live map edits

- book/src/trafficsim/live_edits.md
- game/src/info/person.rs
- game/src/sandbox/dashboards/trip_table.rs
- map_model/src/map.rs
- map_model/src/pathfind/dijkstra.rs
- map_model/src/pathfind/mod.rs
- sim/src/cap.rs
- sim/src/mechanics/driving.rs
- sim/src/trips.rs
instead of aborting the trip.
The demo: With a cap on these roads:
Throughput layer now shows higher traffic on the detour, instead of a bunch of aborted trips:
The edits:
[crazy_cap.json.txt](https://github.com/dabreegster/abstreet/files/5205721/crazy_cap.json.txt)
@michaelkirk
> When a car trip violates a congestion cap, reroute around the problem

- Cargo.lock
- book/src/SUMMARY.md
- book/src/trafficsim/parking.md
- game/src/info/building.rs
- game/src/layer/parking.rs
- sim/Cargo.toml
- sim/src/lib.rs
- sim/src/make/load.rs
- sim/src/make/scenario.rs
- sim/src/mechanics/driving.rs
- sim/src/mechanics/mod.rs
- sim/src/mechanics/parking.rs
- sim/src/router.rs
- sim/src/sim.rs
- sim/src/trips.rs
This adds an `--infinite_parking` flag that assigns unlimited capacity to all buildings, getting rid of the effects of looking for parking far away.
Unresolved bug, will investigate later: the "parking efficiency" layer should just show 0 seconds between car and owner. But at midnight, there are some long paths. Why?
Implementation-wise, this turned out a little more complicated than I hoped. OOP-style, we split into a trait and two implementations. To avoid plumbing the generic everywhere or passing `Box<dyn ParkingSim>` and having a runtime perf hit, using an enum with `enum_dispatch` to do the delegation boilerplate. Alternative ideas:
- Keep the existing implementation and just fill out lots of offstreet spots for every building. EXTREMELY slow to seed parking, open the parking layer, …
> Infinite parking

- game/src/challenges.rs
- game/src/colors.rs
- game/src/common/city_picker.rs
- game/src/cutscene.rs
- game/src/devtools/mod.rs
- game/src/pregame.rs
- game/src/render/area.rs
- game/src/render/map.rs
- game/src/sandbox/dashboards/misc.rs
- game/src/sandbox/dashboards/parking_overhead.rs
- game/src/sandbox/dashboards/summaries.rs
- game/src/sandbox/dashboards/trip_table.rs
- game/src/sandbox/gameplay/mod.rs
- widgetry/src/geom.rs
Followup to #333, which applies textures to some key map elements. These live in the new "textured" color scheme.
This required refactoring some fields of `ColorScheme` to be of type`Fill` instead of `Color`
Starting to look interesting with the experimental isometric buildings! 👀 
**just a GIF showing that it works**
> add textured theme

- game/src/render/building.rs
- widgetry/src/backend_glow.rs
- widgetry/src/drawing.rs
- widgetry/src/geom.rs
- widgetry/src/shaders/vertex_140.glsl
- widgetry/src/widgets/dropdown.rs
- widgetry/src/widgets/menu.rs
**Before**
In the current isometric rendering, there are perspective issues with buildings being rendered on top of eachother in undesirable ways. And note the car parked on the building roof.
Disregard that some of the building's groundfloors juts into the street. As you can see here, it's present in the default rendering, before these changes, and seems to just be bad OSM data:
**After**
Most buildings look good after these changes.
You can see the z-indexes make sense for agents traveling behind the buildings too, as far as perspective goes. But as discussed previously, this might undesirably obscure details of the simulation. Future work which might address this could be some level of transparency, or rotation, or something else.
The thrust of this change is to offset the z-value**, …
> fix building overlap for isometric view (mostly)

- game/src/sandbox/time_warp.rs
Now that it's in its own widget, we need to duplicate some logic
> fix "don't draw" option for jump-to-delay

- game/src/render/building.rs
- map_model/src/make/buildings.rs
- map_model/src/objects/building.rs
Rather than a random building height, we can often pull real building height from OSM:
I found that the reallllly tall buildings looked a little too dominate in downtown areas, so I compressed their height a a bit. 
Here's how it would look without that height compression - WDYT?:
Note that because this adds a field to Building, it requires re-importing map data.
> use osm data for actual building height

- game/src/sandbox/dashboards/mod.rs
- game/src/sandbox/dashboards/parking_overhead.rs
- game/src/sandbox/dashboards/table.rs
- game/src/sandbox/dashboards/trip_table.rs
Yuwen's new dashboard designs make some substantial changes to the trip table and introduces two more tables (cancelled and unfinished trips), each with different columns. To have any chance of keeping up with these design changes, here's an attempt to refactor the current code. The data for each row and the filters are generic structs, and the client code provides a bunch of transformations on these two structs.
I'm not sure how the pop-up filters from the new design will be implemented. Of course, this table API will change again soon to accommodate the new design. But this feels like a step in the right direction of less boilerplate.
There shouldn't be any real behavioral change by this PR.
@michaelkirk
> Refactor trip and parking tables

- game/src/devtools/story.rs
- game/src/edit/mod.rs
- widgetry/examples/demo.rs
- widgetry/src/widgets/button.rs
>  I spot a few more uses of ↑ and ↓ that could be migrated. Either of us could tackle that in a followup
Follow up to https://github.com/dabreegster/abstreet/pull/344, to replace the remaining drop down ↓ with ▾ - sorry that I missed these on the first pass!
Note that though this completes the replacement for drop-down handles, there are still a couple places I intentionally left in the ↑/↓ - controls that are explicitly about direction:
e.g. the increment decrement operations:
e.g. the signal re-ordering
What do you think about keeping these as arrows @dabreegster?
> apply missing pop up button style

- game/src/info/person.rs
- widgetry/src/lib.rs
- widgetry/src/widgets/button.rs
- widgetry/src/widgets/mod.rs
As well as replacing the ↓/↑ with a triangle glyph, also cleans up the pill rendering.
Before:
Zooming in you can see:
- car icon is too large (figma shows the icon and text having about the same height)
- car icon is not vertically centered.
- "ongoing" text is a smidge too low, IMO.
After:
I've pinged Yuwen to double check about the desired rotation of the disclosure triangle when opened vs. close. 
- Previously we rotated the arrow 180 degrees.
- The mockups show no change in "expanded" vs "closed" states
- Conventionally it's a 90 degree rotation, but typically I only see disclosure controls left aligned, so it's not quite comporable.
For now I've stuck with the previous behavior ("up" while closed, "down" while expanded).
> Clean up "trips" (info/person.rs)

- .gitignore
- convert_osm/src/lib.rs
- convert_osm/src/snappy.rs
- game/src/devtools/kml.rs
- kml/src/lib.rs
- map_model/src/raw.rs
A first attempt to snap separately mapped cycleways to main roads. Emit an extra KML file during importing to debug; don't bring into the main map yet. #330
After running `--raw` importer step, go the splash screen > internal dev tools > view KML > load separate_cycleways or snapped_cycleways to see the results.
The Burke Gilman is correctly marked as separate:
Except for this little bit, which correctly matches my intuiton -- the trail becomes part of a wide sidewalk here:
The Roosevelt PBL in the udistrict correctly snaps to the side of the road, except for some funniness where the PBL crosses a right turn lane:
Definitely more work needed, but this initial approach seems reasonable. Rough steps:
1) Test and improve this in more maps
2) For the snapped cases, modify the `RawRoad` and …
> Don't get snappy with me

- widgetry/src/backend_glow_native.rs
- widgetry/src/color.rs
because I significantly indented the unicode diagram, doctest tried to
execute them, and exploded when parsing non-ascii "rust code"
> fix doctest errors 😅 

- Cargo.lock
- Cargo.toml
- book/src/dev/README.md
- convert_osm/src/lib.rs
- convert_osm/src/reader.rs
- importer/src/berlin.rs
- importer/src/krakow.rs
- importer/src/london.rs
- importer/src/main.rs
- importer/src/seattle.rs
- importer/src/tel_aviv.rs
- importer/src/xian.rs
- map_tests/Cargo.toml
- map_tests/src/lib.rs
- map_tests/src/turns.rs
simple .osm, turn it into a full Map, and inspect the results.
I'm not really happy with this approach; specifying the .osm input is pretty low-boilerplate, but then asserting all of the expected turns is going to be a mess. Any ideas?
The synthetic map:
@michaelkirk
> Prototype an idea for unit testing the turn generation code. Hardcode a

- widgetry/examples/demo.rs
- widgetry/src/canvas.rs
- widgetry/src/widgets/mod.rs
- widgetry/src/widgets/panel.rs
Panels calculate their container size and whether or not to show scroll bars based on the canvas size. They do this only once when the panel is first built.
But canvas size changes as window size changes. 
Window size can change manually as the user manually adjusts it, or plugs in an external monitor, etc. But one place this is particularly annoying for me personally is upon first launch. Upon launch the window goes through a series of rapid size changes, starting small and growing to full size (this might just be a macos thing, I'm not sure?).
But this means the panels are all drawn WRT to the initial small size. 
**before**
e.g. look how the top center panel looks broken here:
But even putting the initial launch thing aside, there are a bunch of expected scenarios where the use can …
> update panels and their scrollbars when window resizes

- Cargo.lock
- abstutil/src/serde.rs
- game/Cargo.toml
- game/pkg/index.html
- game/pkg/system
- game/run_web.sh
- game/src/common/city_picker.rs
- widgetry_demo/pkg/index.html
- widgetry_demo/run_web.sh
This is a very strange, specializd approach; it's unclear how it'll
generalize to reading scenarios and prebaked results. Ideally we could
call abstutil::read_binary as we currently do and somehow hide this async
trickery underneath, but I'm not sure how yet. In the meantime, this
moves us forward with the hack well-contained.
Next steps for web: stop bundling in all of data/system in the .wasm,
now that we can load from HTTP.
@michaelkirk
> On the web, load different maps by making asynchronous HTTP calls. #21

- game/src/app.rs
- game/src/info/mod.rs
- game/src/layer/parking.rs
- game/src/layer/traffic.rs
- game/src/lib.rs
- game/src/options.rs
- game/src/render/bus_stop.rs
- game/src/render/map.rs
- game/src/render/mod.rs
- game/src/sandbox/misc_tools.rs
- game/src/sandbox/mod.rs
- geom/src/circle.rs
- geom/src/polygon.rs
- geom/src/ring.rs
- sim/src/lib.rs
- sim/src/sim/queries.rs
Several new players during informal UX tests keep trying to click the unzoomed agent circles. Their use case is that they found someone moving, are interested, and want to get more details about what's happening. It's hard for them to zoom in and find them, especially when the sim is running at high speed. The zoomed agents -- especially tiny pedestrians and bikes -- being hard to click doesn't help.
So this PR adds unzoomed agent selection:
Some caveats:
- won't work for buses (minor, because lots of transit stuff is broken generally right now)
- when you click from this view, it opens the trip panel and centers on them. The automatic centering and snapping feels a bit clunky, especially since it can slightly shift the screen when the agent clicked is already close to center. Should we …
> Allow selecting and clicking unzoomed agents. [rebuild]

- sim/src/mechanics/driving.rs
- sim/src/mechanics/queue.rs
`inner_get_car_positions` is a hot function, and it recurses.  In its hottest invocation (including it's own recursion) we only care about the position of the last car, so we can avoid allocating all the intermediate positions. This complicates the method a a bit, but it's a pretty hefty performance gain: 12-13% less runtime for me.
Command ran:
$ cargo flamegraph --bin run_scenario -- --disable_turn_conflicts --infinite_parking --disable_block_the_box --alerts=silence --disable_recalc_lc data/system/scenarios/downtown/weekday.bin --hours=8
**before**
```
- After 3m26.7s, the sim is at 08:00:00.0. 19,606 live agents
Advance sim to 08:00:00.0 took 206.7296s
run simulation... plus 0.0000s
run simulation took 206.7296s
```
(search highlight is for "malloc" which accounts for most of the …
> perf: only allocate vector for `inner_get_car_positions` when necessary

- abstutil/src/io_web.rs
This file is used in step 6 of the tutorial.
As a desktop app, we had a bunch of files we just read from disk when
needed. Translating this to web requires some thinkging (things are
slower, they can fail, etc.).
As a first step we simply agglomerated all the files into the wasm
binary, but since some of the files are rather large, we tried to only
include the essential and small files.
This one was missed. Though some of the prebaked results files are very
large, this one is a mere 5k.
Longer term, I think we'll want to have the web serve all these files separately, 
but that'll require a bit more thought.
> quick fix crash in tutorial on web

- game/src/app.rs
- game/src/sandbox/mod.rs
@michaelkirk, any thoughts on the odd lifetime of `scenario`? I considered carefully cleaning it up, similar to the calls of `app.set_prebaked(None)`, but I think this way is a little simpler.
> Cache the currently loaded Scenario, instead of re-reading it from the filesystem or (shudder) web. #377

- game/src/app.rs
- game/src/common/minimap.rs
- game/src/lib.rs
- game/src/options.rs
- game/src/sandbox/gameplay/commute.rs
- game/src/sandbox/gameplay/fix_traffic_signals.rs
- game/src/sandbox/gameplay/freeform.rs
- game/src/sandbox/gameplay/mod.rs
- game/src/sandbox/gameplay/play_scenario.rs
- game/src/sandbox/gameplay/tutorial.rs
- game/src/sandbox/mod.rs
- game/src/sandbox/speed.rs
you pass --day_night. Fails to update all panels immediately.
Two concerns:
1) On larger maps, recreating `DrawMap` can take a moment. Suddenly jumping to a loading screen can be a little jarring. Not a huge deal.
2) Panels need to get recreated, to trigger `PanelBuilder::build`, which grabs `ctx.style.panel_bg`. Based on Yuwen's designs, this will also need to change things like text color too. I can think of two general ways to do this. One is the approach half-done in this PR -- recreating the panel from scratch. This loses state like minimap zoom and sandbox speed, and currently doesn't have a nice way of recreating the top_panel for each individual gameplay state. Maybe we just have to pay the cost of adding custom code to a few of these pieces to trigger a panel recalculation, but …
> Automatically toggle between day/night colorschemes at 6am and 6pm, if

- map_model/src/map.rs
- widgetry/src/backend_glow_wasm.rs
> FIX #379: web client resizes with window

- fifteen_min/src/isochrone.rs
- importer/src/soundcast/trips.rs
- map_model/src/pathfind/mod.rs
- sim/src/make/activity_model.rs
@michaelkirk 
I started auditing all of the places in the code that create a `PathRequest` and found this small case to refactor. I'm not sure this is the right abstraction; it's possibly more useful to do something like `map.get_b(bldg).connection_for(PathConstraints::Bike, map)` and `map.get_i(border).start_for(PathConstraints::Car, map)` and `end_for`. But it's a first step, and makes further changes a little easier.
I'm also squinting more closely at sim's `DrivingGoal`. I think it can maybe go away entirely in favor of `TripEndpoint`.
> Refactor PathRequest creators that go between two buildings. #176

- experiment/src/game.rs
- fifteen_min/src/viewer.rs
- map_gui/src/lib.rs
- map_gui/src/simple_app.rs
a key changes.
It's quite verbose right now for some widgetry States to determine if
the mouse is over a particular type of object, check if that object has
changed since the last time, and calculate something based on it. This
introduces a new helper for expressing the pattern a little more
clearly.
@michaelkirk Actually, I think this approach is better. Less boilerplate, works for App/SimpleApp, no weird lifetime issues, more flexible to pass params to key/value functions as needed.
> Start refactoring a common UI pattern: recalculate some value only when

- game/src/app.rs
- game/src/edit/lanes.rs
- game/src/edit/mod.rs
- game/src/edit/select.rs
- game/src/edit/traffic_signals/offsets.rs
- game/src/edit/traffic_signals/picker.rs
- game/src/sandbox/dashboards/traffic_signals.rs
- game/src/sandbox/gameplay/freeform.rs
- game/src/sandbox/misc_tools.rs
- game/src/sandbox/uber_turns.rs
- map_gui/src/lib.rs
selected and clicked on.
@michaelkirk : This adds a few convenience methods to `app` for some commonish cases. In others, more explicitly filter out the valid set of selectable things.
I'm trying to tease apart the ad-hocness of `event()`. Three really common pieces are handling a panel, recalculating the selected map-space thing, and handling clicks on map-space objects.
> Slightly simplify how some states specify what map objects can be

- abstutil/src/logger.rs
- map_model/src/pathfind/mod.rs
- sim/src/mechanics/intersection.rs
- sim/src/mechanics/queue.rs
- sim/src/router.rs
Effectively three behavioral changes:
1. Allow lane changing in an uber turn. Because of the way uber turns work, we lock in and commit to all the lane changes just before entering the uber turn.
2. Avoid overzealous lane changing by combining number-of-lanes-crossed and numer-of-vehicles-in-lane into a single cost, rather than always preferring the least  number-of-vehicles-in-lane.
3. Don't lane-change unless the candidate lane's cost is strictly better than the current lane cost.
Montlake and Lakeslice are affected, but seemingly not by much. In both case the "saved time" slightly outweighs the "lost time". 
I have noticed a pattern where it seems like in general long trips are improved while short trips suffer. I'm not really sure why. One guess would be that previously longer trips …
>     Improve lane changing vis-a-vis uber turns.

- experiment/index.html
- widgetry/src/backend_glow_native.rs
- widgetry/src/backend_glow_wasm.rs
- widgetry/src/runner.rs
It's now easier to understand the possibly slow downloading of the 80MB
.wasm.
Demo:
After the file is loaded, it's possible that instantiating the WASM module is now slower, because now we're not calling [instantiateStreaming](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming). I'm pretty sure I've also seen the progress bar start over; it's maybe possible that `run()` is getting called twice?! I need to dig in more, so this is still just a draft. @michaelkirk, any thoughts about this so far?
There may be some other approaches to continuing to pass in a streamable thing to the WASM loader, but injecting a layer to listen to progress events: https://github.com/whatwg/fetch/issues/607
> Add a progress bar for the initial .wasm loading. #377

- Cargo.lock
- abstutil/Cargo.toml
- abstutil/src/cli.rs
- abstutil/src/logger.rs
- book/src/dev/README.md
It's nice to be able to adjust log levels without re-compiling/linking.
RUST_LOG=debug cargo run --bin game
Note that this can be done on a per lib basis:
RUST_LOG=my_lib=debug cargo run --bin game
a module-by-module basis:
RUST_LOG=my_lib::module=debug cargo run --bin game
And you can mix and match:
RUST_LOG=error,foo::bar=debug,baz=info cargo run --bin game
This is the logging flow that I like - I often spend some significant
time implementing fairly verbose and structured logging while developing
a feature, only to delete it so as not to spam us in general. With this
approach I can leave more of the useful logging in and enable debug
level for just the modules I'm focused on.
Note that this loses the special-case throttling behavior for fastpaths
logging. Now that default level is info …
> replace custom logger with env_logger

- Cargo.lock
- Cargo.toml
- fifteen_min/Cargo.toml
- game/Cargo.toml
- game/src/sandbox/gameplay/census.rs
- geom/Cargo.toml
- geom/src/polygon.rs
- geom/src/pt.rs
- geom/src/ring.rs
- headless/Cargo.toml
- importer/Cargo.toml
- map_gui/Cargo.toml
- popdat/Cargo.toml
- popdat/src/distribute_people.rs
- popdat/src/import_census.rs
- popdat/src/lib.rs
Currently broken - I know at least one reason why (comment inline), but wanted to check in on direction.
This assumes you have a file like this downloaded and in your data/system directory for any city using the census travel model:
[population_areas.geojson.zip](https://github.com/dabreegster/abstreet/files/5683537/population_areas.geojson.zip)
```
{
"type": "FeatureCollection",
"name": "nyc_block_populations",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ 
"type": "Feature", 
"properties": { 
"GISJOIN": "G36000500516005011", 
"population": 123 
}, 
"geometry": { 
"type": "MultiPolygon", 
"coordinates": [ [ [ [ -73.769348000110327, 40.857214999638309 ], [ -73.769408999338665, 40.857162000206102 ], ...] ] ] 
} 
},
...
]
}
```
> census areas import

- game/src/sandbox/gameplay/freeform.rs
- game/src/sandbox/gameplay/mod.rs
- popdat/src/lib.rs
- popdat/src/make_person.rs
- sim/src/lib.rs
- sim/src/make/scenario.rs
Based on #425 so review that first.
Integrates the census based scenario and does some perf work to speed up the census scenario's creation.
Previously it'd take ~440s. 
I got it down to something like 40s by caching the boundary nodes and the activity->building_ids map.
Then down to about 15s by parallelizing the make_person calls.
Oh! And some proof that it works:
> integrate census scenario

- Cargo.lock
- game/src/edit/traffic_signals/edits.rs
- game/src/edit/traffic_signals/mod.rs
- game/src/info/intersection.rs
- map_gui/src/render/traffic_signal.rs
- map_model/src/objects/traffic_signals.rs
- sim/src/mechanics/intersection.rs
Variable provides a min duration, a delay duration, and an additional duration. The maximum cycle time is min + additional. Once min has been exhausted, if there is demand, the cycle is extended by delay until there isn't any demand or the additional duration has been consumed.
Fix divide by zero.
Switch seattle_traffic_signals back.
> Add a Variable phase

- sim/src/mechanics/queue.rs
If an intersection is short, and bike is spawned, another bike coming along will attempt to fit if force_entry is true. This results in a panic. To address this, if the reserved_length is >= the geom_len, false will be returned, even if forced_entry is true.
> Queue::try_to_reserve_entry needs improvement

- Cargo.lock
- Cargo.toml
- README.md
- book/src/trafficsim/travel_demand.md
- game/Cargo.toml
- game/src/sandbox/gameplay/mod.rs
- game/src/sandbox/mod.rs
- geom/src/polygon.rs
- geom/src/ring.rs
- map_gui/Cargo.toml
- map_gui/src/load.rs
- popdat/Cargo.toml
- popdat/scripts/build_population_areas.sh
- popdat/src/distribute_people.rs
- popdat/src/import_census.rs
- popdat/src/lib.rs
Rather than prepping a cropped geojson for each city, I've hosted an agglomerated flatgeobuf file with all the areas and their populations.
Because FGB's are quite efficient, I was able to store the most granular census area: "census blocks". A tract can be several times larger than a block, so getting this more fine grained information should give us a more accurate picture of where trips terminate.
I'm actually optimistic that it would be reasonable to serve other countries population areas in the same unified fgb file, and then we don't need any client changes, per-city handling, or server side logic about which census/population data we want - we "just" need to update the hosted FGB with the new data, and this code which requests based on the WGS84 bounding box will continue to work. …
> fetch US census data from a hosted FlatGeoBuf

- geom/src/duration.rs
- map_model/src/connectivity/walking.rs
To generate more exact costs for buildings in the middle of a sidewalk by adding in distance from the intersection for #393.
> Add dist from sidewalk to cost to improve illustration of distance

- Cargo.lock
- Cargo.toml
- book/src/dev/README.md
- game/src/app.rs
- geom/src/polyline.rs
- map_model/src/make/mod.rs
- map_model/src/objects/road.rs
- sumo/Cargo.toml
- sumo/README.md
- sumo/src/lib.rs
- sumo/src/main.rs
- sumo/src/normalize.rs
- sumo/src/raw.rs
This is the first step exploring integration between SUMO and ABST: a tool to read a .net.xml, then write an abst map. So far, only lanes, intersections, and turns are transformed. There are problems, but the results so far are a start:
The conversion happens in 3 layers:
1) First we just deserialize a .net.xml using `quick-xml` and [serde](https://serde.rs/). No attempt to transform the network structure yet, except for massaging some of the types into `geom`.
2) Normalizing the SUMO network in a few ways. Mainly, resolving missing values by applying defaults or inheriting values from the template [types](https://sumo.dlr.de/docs/Networks/PlainXML.html#type_descriptions)
3) Transforming into an abst map. The main trick here so far is to find two SUMO edges that point opposite directions …
> Convert a SUMO network to an ABST map

- fifteen_min/src/find_home.rs
- game/src/info/person.rs
- game/src/sandbox/speed.rs
- map_gui/src/tools/minimap.rs
- parking_mapper/src/mapper.rs
- santa/src/before_level.rs
- santa/src/music.rs
- santa/src/title.rs
- widgetry/icons/checkbox.svg
- widgetry/icons/checkbox_checked.svg
- widgetry/icons/checkbox_unchecked.svg
- widgetry/src/geom.rs
- widgetry/src/style/buttons.rs
- widgetry/src/widgets/button.rs
- widgetry/src/widgets/checkbox.rs
- widgetry/src/widgets/dropdown.rs
- widgetry/src/widgets/mod.rs
- widgetry/src/widgets/persistent_split.rs
- widgetry/src/widgets/table.rs
- widgetry_demo/src/lib.rs
A little finesse was required to update these button-based controls.
I'm super stoked to have actual checkboxes instead of the `[x]`
> custom buttons: checkboxes and switches

- game/src/info/mod.rs
This was actually a stray local change which I failed to commit before pushing up #467
> translucent background when hovering tab button

- map_gui/src/render/agents.rs
Not 100% ideal because we're using a verb for this mode and a noun for the others (bike,car,bus), but I think it's not that awkward linguistically - I think it's worth it for the tighter panel layout.
**before**
**after**
**alternatively** we could shrink the text size, but it's nice to avoid one-off font tweaks.
> Label "Pedestrian" -> "Walk" for reasonable panel width

- widgetry/icons/checkbox_no_border_checked.svg
- widgetry/icons/checkbox_no_border_unchecked.svg
- widgetry/icons/checkbox_unchecked.svg
- widgetry/src/style/buttons.rs
- widgetry/src/style/mod.rs
- widgetry/src/widgets/checkbox.rs
- widgetry_demo/src/lib.rs
Slightly better contrast for hotkeys in dark mode:
Add stroke to checkboxes:
**before**
**after**
I left the colored checkboxes without a stroke, since it was unnecessary, and felt noisy:
> better hotkey contrast, visible stroke around checkboxes for dark theme

- game/src/devtools/story.rs
- game/src/edit/traffic_signals/mod.rs
I did an audit I believe these to be the last places we were using draw_svg_transform to draw a disabled "button" instead of the new button `disabled` functionality.
> use "disabled" rather than draw_svg_transform

- game/src/lib.rs
@michaelkirk 
I often pass `--dev` and maybe a map on the CLI just to start with an empty map. Since time begins at midnight, that now means dark mode is the default. That's often nice, but I'm a bit more used to the day mode for quick debugging, so I've found myself manually advancing time. This PR changes the default for empty maps to be 6am.
> Start in the daytime when starting on an empty map.

- game/src/info/person.rs
- santa/src/before_level.rs
- widgetry/src/geom.rs
- widgetry_demo/src/lib.rs
It was my intention when introducing the cached vs uncached flavors that
we'd prefer the cached flavor for anything referencing bytes from a
file, like icons and UI glyphs, and that we'd only use the uncached
flavor for dynamic things like "face" generation.
I doubt there's much measurable impact in the couple places we weren't caching, but I didn't want to leave "bad examples" in the code base lest the get copied around.
I renamed `GeometryBatch::from_svg_bytes_uncached` to `GeometryBatch::load_svg_bytes_uncached` to better mirror `GeometryBatch::load_svg` (from path) and introduced a `GeometryBatch::load_svg_bytes` as the "preferred" way to get (and cache) an SVG GeomBatch from bytes.
> Add method to GeomBatch to prefer cached flavor of loading svg.

- data/MANIFEST.json
- game/src/edit/stop_signs.rs
- game/src/info/person.rs
- map_gui/src/render/intersection.rs
Pretty much what the PR title says. Any opinions @michaelkirk, @joeytalbot, @Zireal07?
(There was a suggestion to draw a squiggle when partly zoomed out, but we kind of naturally get that just by rendering the vector text small.)
> Draw 'STOP' on stop signs. Fixes #450

- fifteen_min/index.html
- game/index.html
- osm_viewer/index.html
- santa/index.html
- widgetry_demo/index.html
First step at getting ABStreet working in Safari and on iOS...
The first problem I encountered, is that WebGL 2.0 is not enabled for Safari on mac or iOS by default.
I'm not sure what Apple's timeline is, but it's pretty dire for the graphics stack as currently phrased if it won't work for lots of folks without toggling some obscure setting. e.g. probably not acceptable for embedding in a blog post meant to be easy to consume. I was hoping there was just some bug on our end with the shader version or something. 
For the hardcore fans of abstreet, I've at least included some instructions for how they might get things working.
I've also made some easy changes to the loading screen to make it look a little more like the rest of the app:
Here's what you'll now see when you don't have WebGL …
> draft: More helpful loading screen

- data/MANIFEST.json
- sim/src/mechanics/parking.rs
https://a-b-street.github.io/docs/trafficsim/parking.html#how-people-pick-a-spot describes how things work now. This is a simple step to break up the long "parking snakes" of people all going for the same closest spot in a general area. When flooding out to find other roads with free parking, add a random scaling factor to the cost of each turn. The randomization is deterministic across simulations (as it must be), but seeded from the car ID (so that it differs between vehicles) and starting lane ID (so a particular car doesn't always prefer starting their search by turning left).
Validations that this works well enough:
- The 3 working maps continue to not gridlock
- In North Seattle, I spotted a snake before this change:
but not after:
- The bug originally reports the problem at 6:29 …
> Slightly randomize where people decide to look for parking. #498

- fifteen_min/index.html
- game/index.html
- osm_viewer/index.html
- santa/index.html
- widgetry/shaders/fragment_webgl1.glsl
- widgetry/shaders/vertex_webgl1.glsl
- widgetry/src/backend_glow.rs
- widgetry/src/backend_glow_native.rs
- widgetry/src/backend_glow_wasm.rs
- widgetry_demo/index.html
This (mostly) fixes #502.
The solution is to implement a graphics pipeline for WebGL 1.0, which has been supported by Safari for a while.
> According to https://caniuse.com/webgl, WebGL 1.0 is enabled by default on iOS since iOS 8 (2014)
> According to https://caniuse.com/webgl2, WebGL 2.0 is available, but behind a flag since iOS 12 (2018)
We'll still prefer the WebGL 2.0 backend whenever it's available.
The API's that I used to implement texture handling aren't supported in the older GLSL required by WebGL 1.0. In particular the texture array handling stuff wasn't added until later (e.g. `tex_storage_3d`). I spent a little time trying to back port things to work with the older GLSL version, but I wasn't able to make progress in a reasonable amount of time.
If it's OK with you, I'd …
> WebGL 1.0 support, with automatic fallback for Safari/iOS

- Cargo.lock
- Cargo.toml
- popdat/Cargo.toml
- popdat/src/import_census.rs
It was failing because the version of flatgeobuf we were using was not
compatible with the recent tokio update. Now we point to the unreleased
flatgeobuf which is compatible.
> fix census driven activity model

- game/src/app.rs
- map_gui/src/render/bike.rs
- map_gui/src/render/pedestrian.rs
As discussed in Slack, this is an initial attempt to make it easier to click tiny moving pedestrians and cyclists. It enlarges the hitbox to a circle with 2m radius and draws the hover style as an outline. Additionally, when the hitboxes overlap, pick the agent closest to the cursor.
I considered also implementing for pedestrian crowds, which are always half the sidewalk width, but rarely may grow to be kind of long. But since their shape is so lopsided, not sure how to handle it well (without making some kind of oval). Punting on that for now.
> Use a larger hitbox for selecting pedestrians and bicycles.

- Cargo.lock
- game/Cargo.toml
- game/src/common/mod.rs
- game/src/sandbox/gameplay/freeform.rs
- game/src/sandbox/gameplay/mod.rs
- game/src/sandbox/gameplay/play_scenario.rs
This makes the web experience slightly nicer, letting somebody copy the URL and send it to a friend, and have them at least wind up on the right map or scenario. It doesn't work in general for jumping to a challenge mode or tutorial or arbitrary game state, but I think that's likely overkill -- this covers the common cases.
The simplest test: run locally, open localhost without any query params to get the title screen. Clicking sandbox brings you to the montlake scenario, and now your address bar should reflect this:
> On the web, modify the current URL as we change maps and scenarios.

- game/src/lib.rs
- widgetry/src/assets.rs
- widgetry/src/drawing.rs
- widgetry/src/runner.rs
- widgetry/src/screen_geom.rs
override the default scale factor in order to achieve a minimum width.
Problem: I keep seeing screenshots from people that look like this:
When they force `--scale_factor=1`, things look normal.
Ideal solution: Come up with a proper plan for supporting devices with low width. This is hard, because it requires both redesigning many parts of the UI (sandbox mode panels, dashboard pages, etc) and maintaining multiple layouts in the code.
Workaround: Detect this problem and force scale factor to 1. Retain the ability for people to use the `--scale_factor` flag, if things wind up too small on their screen.
I tested on my device (which can do a factor of 1 or 2). @Robinlovelace has an old Windows laptop that exhibits this problem; I'm guessing compiling this branch there is annoying. If I send …
> On HiDPI screens with low resolution, allow widgetry applications to

- game/src/info/parking_lot.rs
In the info panel, I noticed we usually display plots and titles within a "section" wrapper, like this:
This adds similar "section" styling to the parking lot info panel.
> style parking lot info like other info panels

- game/src/edit/mod.rs
- game/src/sandbox/gameplay/freeform.rs
- game/src/sandbox/gameplay/play_scenario.rs
- map_gui/src/colors.rs
- map_gui/src/render/intersection.rs
- widgetry/src/style/mod.rs
- widgetry/src/text.rs
- widgetry/src/widgets/dropdown.rs
- widgetry/src/widgets/mod.rs
- widgetry/src/widgets/text_box.rs
Before:
After:
In line with figma, removed vertical separator and tweaked alignment
> misc day theme fixups

- game/src/challenges/cutscene.rs
- game/src/edit/mod.rs
- game/src/layer/mod.rs
- game/src/layer/population.rs
- game/src/pregame.rs
- game/src/sandbox/dashboards/misc.rs
- game/src/sandbox/dashboards/mod.rs
- game/src/sandbox/gameplay/commute.rs
- game/src/sandbox/gameplay/fix_traffic_signals.rs
- game/src/sandbox/mod.rs
- game/src/sandbox/speed.rs
- map_gui/src/colors.rs
- map_gui/src/tools/city_picker.rs
- santa/src/before_level.rs
- santa/src/game.rs
- widgetry/src/lib.rs
- widgetry/src/style/mod.rs
- widgetry/src/widgets/image.rs
- widgetry/src/widgets/just_draw.rs
- widgetry/src/widgets/mod.rs
(note the colored separator is fixed seprately in #536)
There should be no visible change for legacy-day and night themes:
> Introduce `Image` component to handle themed icons

- game/src/challenges/cutscene.rs
- game/src/info/mod.rs
- game/src/sandbox/mod.rs
- map_gui/src/colors.rs
- map_gui/src/options.rs
- widgetry/src/runner.rs
- widgetry/src/style/buttons.rs
- widgetry/src/style/mod.rs
I addressed a few lingering things, and I *believe* we're ready to enable day theme by default (🎉)  and ditch the legacy day theme, so I've done that. Let me know if you'd rather wait.
**before**
**after**
**restore button hover state and applied theme text color**
Pregame is kind of a weird beast. The current design isn't really compatible with our new themes, so I haven't tried to make it fit that paradigm. At some point we should redesign it to look more like the rest of the app, but until then I had to hardcode some stuff to keep it looking reasonable.
> Some odds and ends, and enable day theme (!)

- widgetry/src/color.rs
- widgetry/src/screen_geom.rs
- widgetry/src/widgets/panel.rs
- widgetry/src/widgets/slider.rs
The slider was kind of hard to see in the new day theme.
👎 low contrast
👎 transparent button is weird in this context
👎 overlaps neighbors
I also updated the scrollbars to match the design - updating the colors, width, and corner radius.
... for some reason GH video uploading isn't currently working... but here's some screenshots:
> theme slider/scrollbars

- game/src/edit/traffic_signals/mod.rs
- game/src/info/lane.rs
- widgetry/src/style/mod.rs
**before**
**after**
**before**
**after**
> theme fixups

- widgetry/src/screen_geom.rs
- widgetry/src/widgets/button.rs
- widgetry/src/widgets/mod.rs
- widgetry/src/widgets/slider.rs
- widgetry/src/widgets/text_box.rs
Remove unnecessary casts to f64
---
Just a little thing that's been annoying me. I'm not sure why I made this f32 in the first place when most layout stuff is f64.
> make EdgeInset f64, like other layout

- game/src/debug/routes.rs
- game/src/edit/routes.rs
- game/src/edit/traffic_signals/edits.rs
- game/src/edit/traffic_signals/offsets.rs
- game/src/edit/zones.rs
- game/src/sandbox/dashboards/traffic_signals.rs
- game/src/sandbox/gameplay/freeform.rs
- game/src/sandbox/gameplay/play_scenario.rs
- map_editor/src/edit.rs
- map_gui/src/options.rs
- map_gui/src/tools/heatmap.rs
- map_gui/src/tools/minimap.rs
- widgetry/src/widgets/panel.rs
- widgetry/src/widgets/spinner.rs
- widgetry_demo/src/lib.rs
Who could have foreseen problems with my previous fix? 🙄 
> ... I briefly tried to understand why, but gave up and put in a hack that seems to work around the problem.
🤦 
As my penance as well as fixing the crash, I've also attempted to cache the spinner drawable and geeked out on corner rounding of the inner buttons.
> fix spinner crash

- game/src/challenges/cutscene.rs
- game/src/info/intersection.rs
- game/src/info/person.rs
- game/src/sandbox/gameplay/mod.rs
- game/src/sandbox/mod.rs
- game/src/sandbox/speed.rs
- game/src/sandbox/time_warp.rs
- map_gui/src/tools/city_picker.rs
- map_gui/src/tools/colors.rs
- santa/src/before_level.rs
- santa/src/game.rs
- santa/src/meters.rs
- santa/src/title.rs
- widgetry/src/event_ctx.rs
- widgetry/src/geom.rs
- widgetry/src/widgets/compare_times.rs
- widgetry/src/widgets/fan_chart.rs
- widgetry/src/widgets/line_plot.rs
- widgetry/src/widgets/mod.rs
- widgetry/src/widgets/scatter_plot.rs
Mechanical refactor. If you think this is the right direction to go, I vote next renaming `txt.draw(ctx)` and `Line(..).draw(ctx)` to `into_widget` as well.
But for `"normal string".draw_text(ctx)`, what do you think? `text_widget(ctx)`?
> Replace Widget::draw_batch with batch.into_widget, for consistency. #253

- game/src/common/mod.rs
- game/src/info/mod.rs
- game/src/layer/elevation.rs
- game/src/layer/favorites.rs
- game/src/layer/map.rs
- game/src/layer/mod.rs
- game/src/layer/pandemic.rs
- game/src/layer/parking.rs
- game/src/layer/population.rs
- game/src/layer/traffic.rs
- game/src/layer/transit.rs
- game/src/sandbox/mod.rs
- widgetry/src/widgets/panel.rs
Previously, layer panels lived on the right, aligned above the minimap. This worked if your screen is tall enough:
But not always:
Now, all layer panels live on the left side of the screen instead. Because this naturally clashes with info panels, make the two mutually exclusive, only allowing one open at a time. There are no known use cases for having a layer open while following an agent or inspecting an object. And in fact, allowing both simultaneously has unintended consequences of double-drawing to the map -- like showing an agent's route on top of roads highlighted for any reason.
Demo:
The placement of both info panels and layers is pretty arbitrary (the top-left is 2% of screen width, 20% of screen height). I'm up for adjusting that in a followup. One concrete problem is in actdev …
> Move layer panels to the left

- game/src/info/person.rs
- game/src/layer/mod.rs
- game/src/layer/population.rs
- game/src/sandbox/dashboards/misc.rs
- game/src/sandbox/dashboards/mod.rs
- game/src/sandbox/gameplay/commute.rs
- game/src/sandbox/gameplay/fix_traffic_signals.rs
- game/src/sandbox/minimap.rs
- game/src/sandbox/time_warp.rs
- map_gui/src/tools/city_picker.rs
- santa/src/before_level.rs
- santa/src/game.rs
- widgetry/src/lib.rs
- widgetry/src/style/button_style.rs
- widgetry/src/widgets/button.rs
- widgetry/src/widgets/image.rs
- widgetry/src/widgets/persistent_split.rs
- widgetry_demo/src/lib.rs
This is a grab bag of small bug fixes and one big commit. I'd recommend reviewing separately. Here's the description of each commit...
The little triangle is not visible in day theme.
**before**
**after**
traffic curve was barely visible in day theme
**before:**
**after:**
The width traffic curve should match the width of the slider
**before:**
**after:**
The largest commit is intended to be a no-op, but enables one little fix, and hopefully future productivity gains.
I first introduced the concept of `Image` as a means of building buttons - hence `widgetry::buttons::Image`, but there were some places where we wanted to style (color/pad/etc.) images that were not buttons.
I recently duplicated some `widgetry::buttons::Image` functionality to a much simpler `widgetry::Image`, but this PR …
> Move widgetry::button::Image functionality onto widgetry::Image, and some misc. fixes

- game/src/info/trip.rs
Before, the button for showing the route and stats before/after some edits doesn't look like a button:
Since the button lives on a panel, the floating style doesn't make sense.
Switch to outline style:
> Use the outline style for the before/after trip comparison button.

- widgetry/src/widgets/image.rs
In day theme, the minimap's agent toggle icons were not legible.
We now apply default tint to icons unless specified as untinted - this was lost in #568
**before**
**after**
> fixup! Replace ButtonImage with Image

- game/src/sandbox/gameplay/fix_traffic_signals.rs
- map_gui/src/colors.rs
Two separate little fixes.
First commit is the same fix as https://github.com/a-b-street/abstreet/pull/568/commits/d98e2556bc14f445bc725c8f8fd455ccf187403d but for the other challenge: Traffic Signal Survivor.
Second commit  fixes #572
I think eventually we should default to the new day theme for all widgetry apps, but this is slightly non-trivial because `game` still needs to use `pregame` *and* allows overriding the theme in options... 
One eventuality that would simplify things is, when we redesign the pre-game sequence, to do so using styles consistent with day theme and just delete the pregame theme all together.
> icon fix 2

- game/src/sandbox/dashboards/summaries.rs
- bar height represents accumulated time, not trip count
- buckets are from duration *before* edits
> clarify "time difference" chart

- data/MANIFEST.json
- game/src/challenges/prebake.rs
- game/src/debug/objects.rs
- game/src/debug/uber_turns.rs
- map_model/src/connectivity/mod.rs
- map_model/src/objects/zone.rs
- map_model/src/pathfind/ch.rs
- map_model/src/pathfind/dijkstra.rs
- map_model/src/pathfind/driving.rs
- map_model/src/pathfind/mod.rs
- map_model/src/pathfind/pathfinder.rs
- map_model/src/pathfind/vehicles.rs
- map_model/src/pathfind/walking.rs
Access-restricted zones (just "zones" after this) are meant to represent a few situations where "through-traffic" is restricted:
- low traffic neighborhoods (in the UK)
- stay healthy streets (Seattle)
- private/gated neighborhoods (Broadmoor in Seattle)
They're the funny pink colored roads:
If you edit one of them and "change access restrictions", you see the explanation of how they work:
"No through-traffic" means a trip can't cut through the zone. Access only works if the trip begins or ends in that zone. This captures the real-world semantics: residents of that zone can always go in/out, people delivering or visiting can go there, but otherwise, nobody can enter.
The rules for through-traffic are further broken down by mode. For Stay Healthy Streets, for example, the _point_ is to …
> Simplify pathfinding with zones

- map_gui/src/tools/city_picker.rs
- map_gui/src/tools/importer.rs
- widgetry/src/widgets/toggle.rs
- even out the spacing a bit
- use underline style for "Alternate Instructions" web link
- on native, put "download more" before "import your own" since I think we want people to start by downloading an existing one if possible before they try importing.
- "left"/"right" switch is more intuitive than a "right"/"left" switch
**Before: (native)**
**After: (native)**
**After: (web)**
(to show that link-style is maintained)
> Import screen UI fixups

- importer/src/bin/clip_osm.rs
- don't accumulate things unless they are at least partially within the boundary
- accumulate id's, not entire objects.
This entails doing a second pass of the file, but keeps memory usage
much lower.
e.g. a largeish area of Los Angeles, covering east hollywood to downtown, clipped thus:
- north: San Fernando Blvd
- east: LA River east of Downtown
- south: the 10
- west: Western ave,
Before: importing the above stalled out for me during clipping, which
had ballooned into swap at more than 16GB.
After: in the above scenario, clipping peaks around 55MB, and the import
process as a whole peaks during pathfinding - at around 4.0GB.
> PERF: lower memory requirements for clip_osm

- data/MANIFEST.json
- game/src/challenges/prebake.rs
- game/src/debug/routes.rs
- game/src/debug/uber_turns.rs
- map_model/src/connectivity/mod.rs
- map_model/src/pathfind/ch.rs
- map_model/src/pathfind/dijkstra.rs
- map_model/src/pathfind/mod.rs
- map_model/src/pathfind/vehicles.rs
- map_model/src/pathfind/walking.rs
This is simpler to reason about, allows the penalty for entering a zone
or taking an unprotected turn to be expressed in terms of a time
penalty, and is a step towards adjusting bike/foot routing for elevation
data.
When we later add things like "safety/quietness" for cycling, maybe we
can switch to using a (time, quietness) tuple, and transform into a
single number with a linear combination parameterized by that agent's
preference for time/safety. This change is compatible with that future
idea.
There are behavior changes here, particularly for zones and unprotected
turns. Impact on gridlock TBD... Broadmoor proposal TBD...
> Express all pathfinding costs in units of seconds. #82, #494

- game/src/layer/elevation.rs
- game/src/layer/mod.rs
- map_gui/src/tools/colors.rs
Before:
I personally can't really see the steep roads easily with this; the red gradient isn't easy to distinguish.
Now:
This uses the buckets and color scheme from https://github.com/ITSLeeds/slopes.
I considered the 0-3% bucket, but it just adds noise in my opinion. Not coloring the flat roads at all seems nicer. This is the alternative, though:
We happen to get lucky here and the colors work well in night mode too:
CC @Robinlovelace, @eldang, @muzlee1113
> Change the color scheme of the steep streets layer. #82

- game/src/layer/elevation.rs
- game/src/layer/mod.rs
This serves a different purpose from the "steep streets" layer: intuitively see high/low spots in the city.
Smoke test: I can tell that northbound along Fremont Ave is quite a climb, and see the steeper/less steep sections. (Also, Queen Anne is ridiculous.)
I even solved a slight mystery about the flattest way for me to get to Greenwood -- dip below 85th a bit. I've found a slightly more direct route straight up 83rd, but this shows me I could avoid even more hill if I wanted.
Looks reasonable in night mode.
I tried to tune the colors so that you can zoom in and still kind of see the map underneath, but suggestions definitely welcome here!
CC @eldang, @Robinlovelace, @muzlee1113
> Add a layer showing elevation using contours. #82

- game/src/sandbox/dashboards/generic_trip_table.rs
- game/src/sandbox/dashboards/mod.rs
- game/src/sandbox/dashboards/parking_overhead.rs
- game/src/sandbox/dashboards/selector.rs
- game/src/sandbox/dashboards/trip_table.rs
- sim/src/make/spawner.rs
- widgetry/src/lib.rs
- widgetry/src/widgets/mod.rs
- widgetry/src/widgets/panel.rs
- widgetry/src/widgets/stash.rs
- widgetry/src/widgets/table.rs
Use case: for the Broadmoor blog, I want to find all bike/walking trips going from Montlake to Madison Valley, because those're the ones highlighting the problem.
Solution:
I hit a bit of a snag with the widgetry `Table` / `Filters` setup. We want to filter each row by the trip endpoints, so the filter process needs to have two `Option<Polygon>`s for the region to filter by. Right now, the filter struct is created just from the `Panel`, because before today, all of the parameters are directly expressed by checkboxes and dropdowns and such. But to draw the selected region, we need to jump into a new `State`. So, where does the polygon data ultimately live, and how do we plumb it between the trip table and rectangular selection state?
I wound up starting a new pattern in widgetry: the …
> Filter trip table by start/endpoints

- data/MANIFEST.json
- map_model/src/traversable.rs
This PR finally makes use of the elevation data for pathfinding and simulation! Prior to this PR in 892afddcd50ad49daef77060c7cb299fb3fc9fc3 and 20de91bae770f2a6b47ce7d3d3f5b1e4f0af89e8, I refactored all of the places in pathfinding and the simulation that calculate speed of a particular agent along a road. Pathfinding costs are currently expressed in units of time, so we can simply adjust the speed along a steep segment to discourage its use. That same speed is used in the simulation, so pedestrians and cyclists move more slowly.
Details about the function to adjust speed based on incline are in the comments. If anybody knows of something simple to port that might give more realistic results, I'm happy to switch.
CC @eldang and @evansiroky
I spawned some pedestrians and bikes along paths …
> Adjust walking/biking speeds on hills

- data/MANIFEST.json
- game/src/challenges/prebake.rs
- game/src/info/lane.rs
- map_gui/src/render/lane.rs
- map_model/src/edits/mod.rs
- map_model/src/make/mod.rs
- map_model/src/make/turns.rs
- map_model/src/map.rs
- map_model/src/objects/intersection.rs
- map_model/src/objects/lane.rs
- map_model/src/objects/road.rs
- map_model/src/objects/turn.rs
- map_model/src/pathfind/dijkstra.rs
- map_model/src/pathfind/uber_turns.rs
- map_model/src/pathfind/v2.rs
- map_model/src/pathfind/vehicles.rs
- map_model/src/traversable.rs
- santa/src/player.rs
- sim/src/mechanics/car.rs
- sim/src/mechanics/intersection.rs
- sim/src/mechanics/queue.rs
- sim/src/router.rs
- sumo/src/main.rs
There are less directed roads than there are lanes, so there are some performance benefits to changing contraction hierarchies to operate on smaller graphs. For `huge_seattle`, the file size drops from 355MB to 339MB. Time to built all of the contraction hierarchies drops from 1001s to 724s. Both of these are related to the number of nodes in the graph -- 270k before, 112k after. I didn't measure the run-time impact for editing a few lanes and rebuilding the contraction hierarchies, but a smaller graph is likely to help there too.
- I used temporary logging to verify that uber-turns found at the road-level path are preserved in `path_v2_to_v1`, using `south_seattle` to check.
- Since we now cache `Direction` on `Lane`, I reversed some lane directions and verified the internal direction …
> Convert contraction hierarchies to road-based pathfinding v2

- map_model/src/connectivity/mod.rs
- map_model/src/lib.rs
- map_model/src/map.rs
- map_model/src/pathfind/ch.rs
- map_model/src/pathfind/dijkstra.rs
- map_model/src/pathfind/mod.rs
- map_model/src/pathfind/pathfinder.rs
- map_model/src/pathfind/v2.rs
- map_model/src/pathfind/vehicles.rs
- map_model/src/pathfind/walking.rs
- sim/src/cap.rs
The v1 path that all callers need is available by transforming PathV2 to
v1. The plan is to now gradually change callers to natively use PathV2
instead.
There should be no behavior change.
1) I enabled `validate_continuity` to quickly flush out problems in the v2->v1 translation, because it checks that the final path doesn't suddenly warp.
2) I checked there's no diff from prebaked results in montlake
3) I made sure the Dijkstra's impl still works by building the map with `--skip_ch`
Start transitioning all callers to use `pathfind_v2`. From a quick audit, many of them just pathfind to estimate distance or duration of the path or to look for all roads/intersections crossed. That'll be straightforward to port to `PathV2`. Others need to draw the path -- the Slack discussion about showing …
> Start a pathfinding v2 API. #555

- game/src/edit/mod.rs
- map_gui/src/render/intersection.rs
- map_gui/src/render/map.rs
- map_model/src/edits/mod.rs
- map_model/src/make/initial/geometry.rs
- map_model/src/make/initial/mod.rs
- map_model/src/objects/road.rs
- map_model/src/raw.rs
I heard the solution to all traffic problems is more lanes, so here:
The chain of effects is: when we modify a road's width, it affects the polygon of the two connected intersections. That new intersection polygon in turn causes all connected roads to have their center line trimmed differently. Luckily, that's as far as the effect spreads out.
> Road widening, part 2: geometry

- game/src/app.rs
- game/src/edit/mod.rs
- map_gui/src/options.rs
- map_gui/src/render/building.rs
- map_gui/src/render/map.rs
- map_gui/src/render/mod.rs
- map_gui/src/render/parking_lot.rs
- map_gui/src/simple_app.rs
- map_model/src/edits/mod.rs
- map_model/src/make/buildings.rs
- map_model/src/make/mod.rs
- map_model/src/make/parking_lots.rs
- map_model/src/objects/building.rs
- osm_viewer/src/viewer.rs
Previously, sidewalks weren't editable at all, so all of the building and parking lot connections to them were immutable. Now we want to allow changing road width arbitrarily and creating/deleting sidewalks, so this PR does most of the work for updating them.
Demo: first I shrink a road, showing the building paths grow longer. Then I enlarge it, and shrink again, demonstrating the paths respond. If I quit edit mode and resume the sim, it no longer crashes upon sim startup.
- Snapping a building or parking lot to a sidewalk (and driving position, for parking lots) is required. Today we filter out some objects from OSM because this process fails. Now we attempt to correct anything affected by some edits, but when this process fails... what should we do? Currently it just prints a warning …
> Update buildings and parking lots when road width is edited

- game/src/sandbox/gameplay/freeform/grid2demand.rs
- game/src/sandbox/gameplay/freeform/mod.rs
Everything continues to work on Linux for me, for the 3 cases: successfully importing a file, trying to import an invalid file, and cancelling the file dialog. Now the abst UI has the "Waiting for a file" loading screen with a timer, demonstrating true asyncness.
Does this fix it for Mac?
By the way, if you wanted to test e2e, https://github.com/asu-trans-ai-lab/grid2demand/blob/main/dataset/ASU/input_agent.csv is an example input for the `us/phoenix/tempe` map. You also need to `cargo build --release --bin import_grid2demand` for the tool to be found (and if you don't, the error should be reasonable)
> Change the grid2demand file picker to be async. #605

- game/src/debug/mod.rs
- game/src/edit/mod.rs
- game/src/sandbox/mod.rs
- map_gui/src/options.rs
- map_gui/src/tools/minimap.rs
- widgetry/src/widgets/filler.rs
Add an option for hiding UI components except for the minimap and the clock.
I used this for making screen recordings like these:
https://user-images.githubusercontent.com/217057/114930756-390d1980-9dea-11eb-8434-36ff9c6608e2.mp4
In a separate commit I've also made the minimap a fixed size. In particular, it was strange to have the height of the minimap depend only on the _width_ of the window. But now that we are using logical pixels for layout uniformly, I think we'll often get decent simple layouts with fixed sized components.
> minimal controls shown while screen recording

- data/MANIFEST.json
- game/src/info/mod.rs
- game/src/info/trip.rs
- map_gui/src/colors.rs
- sim/src/analytics.rs
- sim/src/events.rs
- sim/src/lib.rs
- sim/src/mechanics/driving.rs
- sim/src/mechanics/walking.rs
- sim/src/recorder.rs
- sim/src/sim/mod.rs
show it in individual trip info panels. #600
I already have lots of UI questions, so this is just a draft.
So far, I'm just showing a count:
Imagine more rows here, like "car wanted to over-take" and "crossed wide, high-speed road".
Should we show the event on the timeline? I'm not too sure how useful it'd be to know that a bunch of "risks" were experienced at the beginning of a trip temporally, and not the end. I'd be more keen to know where they occurred. So I wonder if we should just always draw some markers over the route, like we do already for high delays:
I'm imagining some kind of "caution!" icon. When you hover over it, we describe the issue.
Whatever we decide here, I'm eager to consolidate this concept of a "problem encountered during a trip" both in the UI and code. Right now …
> Track when a pedestrian or bike crosses a large intersection. Start to

- Cargo.lock
- abstio/Cargo.toml
- abstio/src/download.rs
- map_gui/Cargo.toml
- map_gui/src/tools/updater.rs
- rgrep.sh
- updater/Cargo.toml
- updater/src/main.rs
Before: When you download a new city from the native UI -- either by opening a proposal for a map you don't have yet, or by using the "Download more cities" screen -- the entire UI would hang while all of the files are downloaded and uncompressed. The window looks frozen, and the window manager warns as such.
Now: The downloading is async, so the window manager is happy. The loading screen is generic and just has a count of time. On the console, there's a live progress bar with bytes downloaded and such.
Next steps: Plumb that progress bar to the UI loading screen. Then proceed with removing the "Download more cities" screen entirely, and just display all cities in the map loader, whether or not they're downloaded yet. Prompt people to download only when needed.
> Async map downloader for native

- .github/workflows/main.yml
- abstio/src/abst_data.rs
- abstio/src/abst_paths.rs
- game/src/challenges/mod.rs
- map_gui/src/tools/city_picker.rs
- map_gui/src/tools/updater.rs
- santa/src/title.rs
- tests/src/main.rs
- updater/src/main.rs
Before, the .zip native build was about 200MB and included lots -- but not all -- Seattle maps by default. Other cities were available, but you needed to open this giant checkbox list and opt into more places.
Now, the .zip native build is 90MB and just has the default Montlake map. The city picker UI always shows all cities according to `data/MANIFEST.txt`. When you try to open a map that isn't available locally, or start a challenge mode or Santa level with missing data, you're prompted to download.
This shift should have some major benefits:
1) Radically cut down the release .zip size, making initial installation for users and the release process for me easier
2) Simplify the [install procedure](https://a-b-street.github.io/docs/howto/asu.html#installing) for somebody trying to grab a …
> Pretend like all maps are available in the native UI, download when needed

- Cargo.lock
- game/Cargo.toml
- game/src/sandbox/gameplay/freeform/grid2demand.rs
- game/src/sandbox/mod.rs
- map_gui/src/load.rs
- map_gui/src/tools/updater.rs
And at last, the end-to-end UX for downloading a new city on native isn't so clunky!
> Progress bar for native downloads

- map_gui/src/colors.rs
**before**
**after**
This might be controversial, we don't have to do it, but I feel like the mostly grey stop-signs look strange.
/cc @muzlee1113
> make stop signs more red at night

- game/src/debug/routes.rs
- game/src/edit/routes.rs
- game/src/edit/traffic_signals/edits.rs
- game/src/edit/traffic_signals/offsets.rs
- game/src/edit/zones.rs
- game/src/sandbox/dashboards/traffic_signals.rs
- game/src/sandbox/gameplay/freeform/spawner.rs
- game/src/sandbox/gameplay/play_scenario.rs
- map_editor/src/edit.rs
- map_gui/src/options.rs
- map_gui/src/tools/heatmap.rs
- map_gui/src/tools/minimap.rs
- widgetry/src/widgets/panel.rs
- widgetry/src/widgets/spinner.rs
- widgetry_demo/src/lib.rs
Long over-due cleanup.
Note this slightly alters the appearance of spinners; we use the normal method to display durations, distances, etc:
There have been requests to focus on a spinner and type in the value. Switching to generic types makes this a little more complicated when we get around to it, but not by much -- we just need a way to parse `&str -> Option<T>`
> Store a generic type in the Spinner widget.

- game/src/edit/traffic_signals/mod.rs
We've seen a few people pretty confused by clicking the arrows in the signal editor. One user even expected to click or right click a movement and get a menu of actions.
A simple thing Yuwen and I discussed is just adding tooltips. This information is in the OSD at the bottom, but it's too far away from where people are looking.
Before:
After:
I don't know if "protected" and "permitted" are the best terms to use here, but they're succinct at least. We also talked about adding a help screen to the signal editor with a legend, to define terms and hopefully clarify things a bit.
> Add tooltips to the signal editor.

- fifteen_min/src/find_home.rs
- fifteen_min/src/isochrone.rs
- map_model/src/connectivity/mod.rs
- map_model/src/connectivity/walking.rs
Background: https://a-b-street.github.io/docs/side_projects/fifteen_min.html#finding-the-perfect-home
Before, this tool was comically brute-force. In West Seattle, selecting food, supermarkets, and cafes, it takes my sad laptop 57s to do this, totaling 202 runs of Dijkstra.
After, 8s and just 3 searches (1 for each category).
No behavioral change.
> Speed up the 15m perfect home finder

- .dockerignore
- abstio/src/abst_data.rs
- cloud/Dockerfile
- cloud/import_one_city.sh
- cloud/start_batch_import.sh
- updater/src/main.rs
See https://github.com/a-b-street/abstreet/issues/326#issuecomment-832096798 for context. When certain parts of the code change, we have to rebuild all maps. I want to stop running `data/regen.sh` and frying my poor laptop. Instead, I want to import each city in parallel in the cloud.
This is a simple first step to get the importer and updater working inside a Docker container. Running `./cloud/start_batch_import.sh some-new-map-feature` creates a Docker image with local code changes. That container has a script that'll eventually run, `import_one_city.sh some-new-map-feature jp/hiroshima` that'll download some existing input data and build Hiroshima. Some next steps are to upload that to a temporary place in S3 (not the `dev` subdirectory that everything live uses), farm out the AWS …
> First steps towards importing maps in the cloud

- game/src/pregame/proposals.rs
- game/src/sandbox/time_warp.rs
- widgetry/src/screen_geom.rs
- widgetry/src/widgets/button.rs
- widgetry/src/widgets/mod.rs
- widgetry/src/widgets/panel.rs
The "skip draw" box is an option that you can set before initiating a time warp. By skipping drawing, we save some computational costs, allowing the simulation to run faster and get to it's warp destination sooner.
However, I often start the time warp, only to realize that I forgot to check the "skip drawing" box, so I have to then decide to just forge ahead warping at a slower pace, or cancel to re-start the time warp with the proper option.
This PR, moves the "skip draw" option to after you start warping, so you can toggle it off and on while warping.
An added benefit of this is you can momentarily toggle it to peak at the map state without stopping the warp altogether.
https://user-images.githubusercontent.com/217057/117900504-24536280-b27e-11eb-890c-18c7e53529ee.mp4
> time warp ergonomics

- fifteen_min/src/find_amenities.rs
- fifteen_min/src/isochrone.rs
- fifteen_min/src/lib.rs
- fifteen_min/src/viewer.rs
This adds a button to the main 15min neighborhood panel which launches a separate viewer to examine a multi starting point isochrone where each starting point is an amenity of a certain type. For example, if there are 20 car repair buildings and a user chooses car repair then there will be 20 starting points (car repair buildings) with isochrones drawn around each. This is all done with a single new isochrone call just with a vector of starting points instead of a single start (how it was before). Because of this, the main viewer mode now passes in a vector of length 1 to create an isochrone.
As a user hovers over buildings the closes amenity is determined and a path is shown with a time to that building (this is currently a bit slow in dev mode, maybe needs to be faster?).
I did not put …
> Add a search by amenity mode to 15min using multi start points

- Cargo.lock
- abstutil/src/utils.rs
- game/Cargo.toml
- game/src/edit/roads.rs
- game/src/info/trip.rs
- game/src/sandbox/dashboards/mod.rs
- game/src/sandbox/dashboards/risks.rs
- game/src/sandbox/dashboards/summaries.rs
- game/src/sandbox/minimap.rs
- widgetry/src/geom/geom_batch_stack.rs
- widgetry/src/lib.rs
- widgetry/src/widgets/button.rs
- widgetry/src/widgets/mod.rs
trip duration. #600
The goal is to show how trips of different lengths encounter more or less problems due to map edits. Looks like this:
I still need to add labels, but the X-axis is trip duration and the Y-axis is the relative number of problems encountered, with green meaning less (good) and red meaning more (bad). The number of trips matching that duration range and relative problems is shown in each cell.
You can try this out by doing `cargo run --release -- --dev ../data/system/us/seattle/scenarios/arboretum/weekday.bin --edits='broadmoor access'` (after running the updater, because the prebaked data just changed), running for a while, then opening up the new "risk exposure" dasboard
@michaelkirk, @Robinlovelace, and @julianmichael (this was Julian's idea originally, for comparing …
> Create a contingency matrix showing how number of problems change per

- fifteen_min/src/viewer.rs
- game/src/info/trip.rs
- game/src/sandbox/dashboards/mod.rs
- game/src/sandbox/dashboards/risks.rs
- game/src/sandbox/dashboards/travel_times.rs
- game/src/sandbox/dashboards/trip_problems.rs
- game/src/sandbox/gameplay/play_scenario.rs
- osm_viewer/src/viewer.rs
- widgetry/src/event_ctx.rs
- widgetry/src/widgets/mod.rs
As promised, I've added the "Delays Matrix" to the "Travel Times" dashboard.
> Add "Intersection Delays" matrix to "Travel Times" dashboard

- game/src/edit/mod.rs
- game/src/edit/multiple_roads.rs
- game/src/edit/roads.rs
Today, we have a tool to bulk edit many lanes at once. You select a bunch of roads, and then just blindly search/replace from one lane type to another:
This has pretty limited use, from my knowledge. And now that we have a more detailed road-wide editor, we can do better.
With this new tool, I can first modify one road, changing the parking lane on either side to a bike lane. Then I hit "edit multiple", and the UI automatically finds **all** roads in the map that look similar to the road I originally edited -- same number and type of lanes from before my edit. By default, it starts me with just the subset of these roads that have the same name as my original road. But other roads throughout the map that look similar are highlighted, and I can opt them in as well by clicking to …
> Bulk road edit

- data/MANIFEST.json
- map_model/src/edits/mod.rs
- map_model/src/make/mod.rs
- map_model/src/objects/road.rs
the new road editor, by "untrimming" the road center points. Fixes #655
Before, you could pick a single lane and shift it left and right repeatedly, with the intersection polygon becoming subject to increasingly Lovecraftian geometry:
Truly the stuff of horrors.
Now, Cthulu has been coaxed back into the salty depths:
@tungchifung, if you happen to be building from source, feel free to checkout this branch and test it out. If not, it'll appear in this Sunday's release
> Fix the "growing intersection" bug that happens when repeatedly using

- game/src/debug/mod.rs
- game/src/info/trip.rs
- game/src/layer/problems.rs
- game/src/sandbox/dashboards/risks.rs
- game/src/sandbox/dashboards/trip_problems.rs
- map_model/src/objects/turn.rs
- sim/src/analytics.rs
Similar to the cyclist-specific metrics, add a new metric for pedestrians crossing across or along an arterial intersection.
Here's a new debug tool, highlighting arterial intersections:
And here's the same-old risk matrix, in a new "pedestrian risks" section.
> ped safety: arterial crossings

- data/MANIFEST.json
- game/src/info/lane.rs
- map_model/src/make/mod.rs
- map_model/src/make/turns.rs
- map_model/src/objects/lane.rs
- map_model/src/objects/turn.rs
- tests/goldenfiles/divided_highway_split.txt
- tests/goldenfiles/left_turn_and_bike_lane.txt
- tests/goldenfiles/multiple_left_turn_lanes.txt
- tests/src/main.rs
The story of this PR is one of yakshaving. I started by trying to detect routes that work with pathfinding v2 (at the road segment level), but not v1 (the lane level), assuming that most of these would be paths that start with an immediate left turn from a far lane. But instead, I discovered a bunch of lanes that were "orphaned" -- either they would dead-end and have 0 outgoing turns, or they weren't actually reachable from anything.
Particularly this little case:
What's going on with https://www.openstreetmap.org/way/459084306 is that `turn:lanes = left|right`, but this tag is marked on the segment of the road that terminates at the separately mapped bike/foot path. We faithfully apply these turn restrictions, so from the road, you can only go left or right onto the bike path, and can't …
> Improved turn generation for vehicles

- data/MANIFEST.json
- game/src/app.rs
- game/src/challenges/prebake.rs
- game/src/debug/mod.rs
- game/src/edit/traffic_signals/edits.rs
- map_model/src/connectivity/mod.rs
- map_model/src/edits/mod.rs
- map_model/src/lib.rs
- map_model/src/make/mod.rs
- map_model/src/map.rs
- map_model/src/objects/intersection.rs
- map_model/src/objects/stop_signs.rs
- map_model/src/pathfind/walking.rs
- sim/src/mechanics/driving.rs
- sumo/src/main.rs
- tests/src/main.rs
Minimal file size savings, but substantial runtime improvement!
See https://github.com/a-b-street/abstreet/issues/368#issuecomment-849891303 for context on this idea.
I ran montlake in headless mode a few times:
- before: 17.8s, 20.6s, 21.3s, 17.9s
- after: 13.4s, 13.1s, 15.5s, 14.0s
Quite a bit of variance there, but consistently this new approach is faster.
More dramatically... a single run of `game --prebake` drops from 12m36s to 9m11s!
Not very much -- lakeslice from 25MB to 24MB. All we're saving is all of the `TurnIDs` being listed twice, from the old `BTreeMap`.
I was curious if we could squeeze down `TurnID` when serializing from 3 u32's (the intersection, src lane, dst lane). In huge_seattle, we have about 265k lanes and 41k intersections. 19 bits could fit about 1 million lane …
> Store Turns per Intersection, instead of a massive BTreeMap. #368

- fifteen_min/src/find_amenities.rs
- fifteen_min/src/find_home.rs
- fifteen_min/src/isochrone.rs
- fifteen_min/src/viewer.rs
- map_model/src/connectivity/mod.rs
- map_model/src/connectivity/walking.rs
Here is my first pass at adding the BorderIsochrone functionality. The purpose of this is to make it clear to the user of the Find Amenities portion of the 15min tool that buildings close to the map boundary may actually contain the amenity they are looking for but because the amenity would exist off the map we have no way of knowing. The one part I was confused about are the thresholds for the polygons being drawn, right now I think the black border isochrones are not the right distance.
- Add a Spot enum which can contain a Building with a BuildingID or a Border with an IntersectionID
- Refactor `connectivity::all_walking_costs_from` and `connectivity::all_vehicle_costs_from` to take a `Vec<Spot>`
- Refactor the current Isochrone code by pulling out the `draw_isochrone()` function and …
> Generalized connectivity to use Spot and added BorderIsochrone

- game/src/sandbox/gameplay/play_scenario.rs
- sim/src/analytics.rs
- sim/src/lib.rs
- sim/src/sim/queries.rs
Refactor some of the sliding window code along the way.
Common problem: you start a scenario, but it's quiet at midnight, and you have no idea when trips will even start. If we happen to be lucky enough to have prebaked data for the scenario, then you can figure this out with the "active traffic" dashboard, which is hidden away.
Solution: add a little info button to the scenario panel:
It just shows how many trips start over the day. Soundcast example:
And grid2demand -- now it's easy to understand why the simulation grinds to a halt suddenly, no spread!
There's also a shortcut from the new screen to see more detailed commuter patterns. And if you open the panel when nothing's happening, there's a shortcut to time-warp to the first trip.
> Create a new panel to show how trips are distributed through the day.

- data/MANIFEST.json
- map_model/src/pathfind/v1.rs
- sim/src/mechanics/car.rs
- sim/src/mechanics/driving.rs
- sim/src/mechanics/queue.rs
- sim/src/router.rs
I'm more than a little sentimental about this PR, because it's conceptually simple, but is a massive step towards fixing one of the biggest simulation limitations in A/B Street. There's a history to the discrete event system we currently use; according to git, most of it was created February 19-27 of 2019. (And there was a crazy attempt to model smooth acceleration the week before that, but I gave up.) Mostly I've tried to not touch the queue and discrete event stuff since then. Well over two years later, I managed to shove it all back into my head and figure this out.
I want to write a full/proper article with diagrams to explain how everything works. Until then, here's the gist of it, assuming familiarity with how things work now: …
> Dynamic lane-changing

- game/src/sandbox/dashboards/travel_times.rs
- game/src/sandbox/dashboards/trip_problems.rs
- widgetry/src/geom/geom_batch_stack.rs
- widgetry/src/style/mod.rs
The existing contingency matrix rely heavily on mouse-over for context. This made grabbing a screenshot of them not very useful. Adding axis labels for the bucket divisions helps.
With slow compile times and only pretty low level graphics layout apis, this ended up taking an embarrassingly long time. =(
> Label contingency matrix axes

- Cargo.lock
- data/MANIFEST.json
- game/src/debug/objects.rs
- map_model/Cargo.toml
- map_model/src/pathfind/v1.rs
- map_model/src/pathfind/v2.rs
- map_model/src/pathfind/vehicles.rs
- sim/src/mechanics/car.rs
- sim/src/mechanics/driving.rs
- sim/src/mechanics/queue.rs
- sim/src/trips.rs
This adds support for vehicles to exit buildings or parking lots and immediately take a left or right turn to any lane. This vastly improves the realism of some routes. Before:
After:
No impact on gridlock -- things generally get a little better, with shorter routes. The new `tests/goldenfiles/prebaked_summaries.json` also makes sure we didn't suddenly cancel lots of trips.
Going to merge this ASAP, just recording notes here.
Some next steps:
- handle entering a driveway from either side at the end of a trip
- then revisit the concept of parking blackholes, since many buildings will effectively be connected to the map, even if they're close to a border
- explore how to use center turn lanes
#555
> Exit driveways from either direction

- game/src/info/trip.rs
- game/src/layer/elevation.rs
- geom/src/distance.rs
- widgetry/src/widgets/line_plot.rs
map's max height. This helps compare elevation profiles before/after map
edits.
Example of a comparison now:
Dividing the max value by 3 is still quite unfortunate...
> Use a fixed maximum for the Y scale of the elevation profile, based on a

- game/src/sandbox/dashboards/travel_times.rs
- geom/src/duration.rs
- widgetry/src/widgets/compare_times.rs
Add y-axis labels to the aggregate duration chart.
**before**
**after**
(only the left chart changed)
> label y-axis for aggregation duration charts

- Cargo.lock
- map_gui/Cargo.toml
- map_gui/src/load.rs
- web/README.md
On the web, loading a file just shows "time spent", with no indication of total file size or how much we've received. I've tried puzzling through the APIs for receiving chunks before, but never figured it out. I found https://crates.io/crates/wasm-streams recently, which appears to make it work!
The 1MB choppiness is because I'm testing locally using https://stackoverflow.com/questions/13654663/how-can-i-serve-http-slowly.
> Include bytes received for web file loaders

- abstio/src/abst_paths.rs
- abstutil/src/clone.rs
- abstutil/src/collections.rs
- abstutil/src/lib.rs
- game/src/app.rs
- game/src/common/mod.rs
- game/src/info/intersection.rs
- game/src/info/trip.rs
- game/src/sandbox/dashboards/commuter.rs
- game/src/sandbox/dashboards/misc.rs
- game/src/sandbox/dashboards/mod.rs
- game/src/sandbox/dashboards/risks.rs
- game/src/sandbox/dashboards/traffic_signals.rs
- game/src/sandbox/dashboards/travel_times.rs
- game/src/sandbox/dashboards/trip_problems.rs
- game/src/sandbox/minimap.rs
- game/src/sandbox/speed.rs
- map_gui/src/load.rs
- map_gui/src/tools/city_picker.rs
- sim/src/lib.rs
- widgetry/src/app_state.rs
- widgetry/src/lib.rs
- widgetry/src/widgets/containers.rs
- widgetry/src/widgets/image.rs
- widgetry/src/widgets/just_draw.rs
- widgetry/src/widgets/mod.rs
- widgetry/src/widgets/panel.rs
At last, we can more easily explore what trip managed to have more arterial crossings with the Broadmoor proposal. The risk matrix cells are now clickable:
(Actually comparing that trip to before the proposal crashed, looking into that problem now!)
Clicking a cell opens up the trip info for one arbitrary member of the cell. I'm not sure what a better UX would be, but I'll explore it in a followup. Maybe opening a trip table with columns focused on problems. This also raises the question of how to return to the problem matrix after checking a trip. I actually want to do that with the trip table all the time -- I set up filters, click on a particular trip, but then want to return to the dashboard. I'm considering making the dashboard more stateful when returning back to it.
> Sample trips from the risk matrix

- convert_osm/src/split_ways.rs
- data/MANIFEST.json
- game/src/challenges/prebake.rs
- map_editor/src/model.rs
- map_model/src/edits/mod.rs
- map_model/src/make/initial/geometry.rs
- map_model/src/make/initial/mod.rs
- map_model/src/make/mod.rs
- map_model/src/raw.rs
- tests/goldenfiles/prebaked_summaries.json
Today is a pretty damn good day.
#654 describes how we merge short roads and produce the intersection polygons today. This PR implements "wild alternative number 1," which isn't so crazy after all. The idea is to first run the normal intersection geometry algorithm before removing any of the short roads. That tells us how much to trim back all of the connected roads. We calculate that trimmed endpoint, **then** remove the short road. To produce the polygon for a consolidated intersection, we simply take the pre-trimmed road center lines, project the left and right, and use those endpoints as corners of the polygon.
A huge amount of trial-and-error and fiddling around went into this. A few things were absolutely necessary to iterate effectively:
1) a fast compile+import map process. My …
> Overhaul intersection consolidation

- Cargo.lock
- Cargo.toml
- game/src/sandbox/dashboards/commuter.rs
- geom/src/lib.rs
- geom/src/polygon.rs
- geom/src/polyline.rs
Also, for sidewalks, interpolate points every n-meters to get a better concave hull.
Be aware, that this is noticeably more expensive than the convex hull calc for dev builds, but there's no perceptible slowdown for release builds.
**before:**
**after:**
**note:**
This currently relies on an unmerged/unreleased PR:
I'm happy to either: 
- merge this and run geo from my branch (there aren't really any other relevant changes for abstreet)
- wait for that PR to get merged, and then I could probably quickly wrangle out a geo release that abstreet could update to.
> Use concave hull for neighborhoods

- data/MANIFEST.json
- map_gui/src/render/intersection.rs
This is a followup to @westnordost's suggestion in #704 to draw a more explicit curb between the road and sidewalk. I incorporated a few more ideas here too, pulling lots of colors from Streetcomplete (https://user-images.githubusercontent.com/7988080/103153247-827c1f00-478f-11eb-9d1f-4d12017533aa.png) and also its map style (https://raw.githubusercontent.com/ENT8R/streetcomplete-mapstyle/gh-pages/images/light.png). I'm **really** liking how things are looking and am considering a big color overhaul based around this. Any initial feedback? @Robinlovelace, @michaelkirk, @trangrei
Some of the changes:
- Using Streetcomplete colors for the map background, water, parks, unzoomed roads
- Drawing a bold line between the road and curb. (There are some bugs near intersections that I'll fix if we …
> Quick prototype of Streetcomplete colors and an explicit curb

- widgetry/src/backend_glow_native.rs
A screenshot or gif isn't high-resolution enough to demonstrate the problem. But from your current copy, zoom out on a map and slowly zoom in. On my machine, the new road/intersection outlines have a jagged tearing effect. After increasing the MSAA value here, the tearing improves significantly.
I couldn't find a clear answer for what MSAA values are common and well-supported, but https://en.wikipedia.org/wiki/Multisample_anti-aliasing#Quality says modern GPUs support 8. So if this change also looks better and works on your system, I vote we go for it.
> Increase multisampling to fix unzoomed road outline tearing

- game/src/ungap/mod.rs
- widgetry/src/canvas.rs
- widgetry/src/style/mod.rs
- widgetry/src/widgets/button.rs
https://user-images.githubusercontent.com/217057/130282684-dc6e4a9c-fcd4-4f84-a0a1-45f7bca96aca.mp4
It disabled at max/min zoom, whether you clicked or scrolled to zoom.
For now I've just added this into the ungap tool view, but it might make sense to add something like this to the main tool as well. 
The reason I didn't, was my fear that it would be confusing to have such similar buttons next to the minimap, which has it's own internal zoom controls.
> map explorer: add zoom buttons near legend

- game/src/edit/roads.rs
- map_gui/src/lib.rs
- widgetry/src/app_state.rs
- widgetry/src/geom/geom_batch_stack.rs
- widgetry/src/geom/mod.rs
- widgetry/src/lib.rs
- widgetry/src/screen_geom.rs
- widgetry/src/widgets/drag_drop.rs
- widgetry/src/widgets/image.rs
- widgetry/src/widgets/mod.rs
- widgetry/src/widgets/panel.rs
- widgetry_demo/src/lib.rs
supersedes #673 
This was especially tricky because it:
1. introduced the drag-and-drop cards widget
2. synchronizes that widget with hover and click state from the map
https://user-images.githubusercontent.com/217057/130533023-d53f8c0b-3c5c-43bd-974f-a05252a571ae.mp4
> drag-and-drop lanes in editor

- game/src/ungap/mod.rs
**before**
The "filemanagement" controls are smashed against the section border.
**after**
Using the `Widget::section(self, ctx)` method adds the section background, padding, and outline.
> sections should have padding

- game/src/ungap/bike_network.rs
- game/src/ungap/layers.rs
- widgetry/src/geom/mod.rs
highlight road types better.  #743
@trangrei, please let me know if this addresses the highlighting problem you mentioned, and if you have any further suggestions
1) When you disable the bike network layer, the "dark fade" went with it. But then the road labels become illegible. They're white text with a black outline, pretty tuned to the "dark fade".
2) If you hover over the legend, we highlight different road types in cyan. It succeeds at grabbing attention, but the new color is unrelated to each road type and kind of weird.
1) Always draw the dark map fade
2) Use the road type colors when highlighting. For the 4 different bike types, always just use green, since some of the more faded shades of green don't call enough attention.
The 4 bike types are a hierarchy from good to bad: trail …
> Improve the bike network tool's colors. Always draw the fog-of-war, and

- Cargo.lock
- map_model/Cargo.toml
- map_model/src/pathfind/engine.rs
According to measurements in fast_paths with the new parameters the preparation (initial + with node ordering) should be faster. 
Also see this discussion: https://github.com/easbar/fast_paths/pull/37
I have not tried this in abstreet yet, what is the best way to do so?
> Update fast_paths to current master, faster preparation

- game/src/debug/mod.rs
so trying to use the merge tool in the debug menu resulted in
```
[2021-11-05T13:15:15Z INFO  map_gui::tools::command] RunCommand: ./target/release/cli import --map fordham --city=us/nyc --skip_ch
> error: Found argument '--skip_ch' which wasn't expected, or isn't valid in this context
>       Did you mean --skip-ch?
> 
> USAGE:
>     cli import --city <city> --map --skip-ch
> 
> For more information try --help
> 
```
> structopt changed underscore options to hyphen

- map_gui/src/render/lane.rs
Right now one-way arrows and turn markings look very similar and it is easy to get them confused. This patch makes the one-way marking outline arrows. This is common in road drawings.
> Make one way marking arrows outlines

- map_gui/src/tools/mod.rs
Fixes #814 
My guess is that when @Robinlovelace encountered the error, they hadn't yet built the CLI binary. 
The expected behavior is that when a helper program is missing, the program will crash with a somewhat helpful error message. That's not a *great* user experience, but it's slightly better than the cryptic "permission denied" error seen in #814.
The reason we weren't seeing that error message in this case is that when `find_exe` looks for the `cli` binary, we incorrectly thought we'd found in when in fact we'd just found the `cli` directory and then (of course) failed to execute it.
> fix: a directory is not an executable

- data/MANIFEST.json
- map_model/src/make/initial/geometry.rs
- map_model/src/objects/block.rs
Seemingly fix all "bowtie" intersections, where the polygon looped back
on itself impossibly. Achieve this by sorting polylines around a center
more carefully.
Regenerating all maps...
> Bowties belong on necks, not at intersections

- game/src/ltn/browse.rs
- game/src/ltn/mod.rs
- game/src/ltn/select_boundary.rs
- game/src/ltn/viewer.rs
- map_model/src/objects/block.rs
- widgetry/src/mapspace/world.rs
Still need to think through the UX of how to manage custom boundaries
and incorporate them in the "browse neighborhoods" screen.
Demo:
Context here is that defining the "boundary" of a neighborhood is hugely contentious. What if people want to "merge" two adjacent LTNs? What if the OSM classification of a major road is wrong? What if the government's inclusion of some road as a major arterial road is based on historic context and should be challenged now? Should the boundary of an LTN include parks, waterways, railroads or not -- https://github.com/a-b-street/abstreet/issues/794#issuecomment-963474633?
Instead of trying to decide all of this by heuristic, just let the user paint their own boundary!
The UX is clunky right now -- after you draw a boundary, it won't be "saved" to the "browse …
> Draw custom LTN boundaries, by painting blocks. #794

- Cargo.lock
- data/MANIFEST.json
- geom/src/line.rs
- map_gui/Cargo.toml
- map_gui/src/render/bike.rs
- map_gui/src/render/lane.rs
- map_gui/src/render/pedestrian.rs
- map_gui/src/render/turn.rs
- map_model/Cargo.toml
- map_model/src/make/turns.rs
- map_model/src/objects/turn.rs
1. Use Bezier curves for all turns, so a lane change is now an offset bend instead of a straight line.
2. Change turn::angle to be the relative angle of the turn (i.e. +90 degrees is a normal left turn)
3. Draw turn marking arrows prettily using Bezier curves
> Curvy turn arrows

- cli/src/main.rs
this fixes the difference between the tool and the docs, where currently the tool expects geo-json-to-osmosis.
> Add structopt option to change derived name of geojson-to-osmosis

- data/MANIFEST.json
- map_model/src/make/walking_turns.rs
a degenerate intersection on a street with only one sidewalk generates both a crosswalk and a SharedSidewalkCorner
_Originally posted by @mdejean in https://github.com/a-b-street/abstreet/issues/816#issuecomment-997029499_
> Delete the crosswalk at degenerate intersections with sidewalks on one side

- game/src/ltn/connectivity.rs
- game/src/ltn/draw_cells.rs
- game/src/ltn/mod.rs
- game/src/ltn/per_neighborhood.rs
- map_model/src/pathfind/mod.rs
- widgetry/src/color.rs
Problem: there's a bike/foot-only road in the middle of the blue area, so the partitioning into cells is wrong:
This PR treats roads inaccessible to cars as already filtered. Now we get:
Which is better, but there are some issues exposed... The view by streets maybe shows it a little better:
I'm not sure how to classify non-motorized roads. The point of a cell is to show all the contiguous area a driver can reach without leaving the neighborhood. Maybe the "cells" based on already-filtered roads should just be invisible, treated as internal gaps in the neighborhood?
When we start looking at measurements based on all buildings with the neighborhood -- such as how far do they have to drive to reach the perimeter -- we'll have to do something about buildings snapped to a non-motorized road …
> When calculating LTN cells, don't cross bike-only roads.

- abstutil/src/collections.rs
- game/src/debug/routes.rs
- game/src/lib.rs
- game/src/pregame/mod.rs
- game/src/pregame/proposals.rs
- game/src/ungap/predict.rs
- game/src/ungap/trip/results.rs
- geom/src/distance.rs
- geom/src/stats.rs
- ltn/src/browse.rs
- ltn/src/filters.rs
- ltn/src/impact.rs
- ltn/src/impact/mod.rs
- ltn/src/impact/ui.rs
- ltn/src/lib.rs
- ltn/src/pathfinding.rs
- ltn/src/per_neighborhood.rs
- ltn/src/rat_runs.rs
- map_gui/src/tools/colors.rs
- map_gui/src/tools/mod.rs
- map_gui/src/tools/ui.rs
- map_model/src/connectivity/mod.rs
- map_model/src/lib.rs
- map_model/src/map.rs
- map_model/src/pathfind/mod.rs
- map_model/src/pathfind/pathfinder.rs
- map_model/src/pathfind/vehicles.rs
- sim/src/make/scenario.rs
Similar to Ungap the Map's [predict impact](https://a-b-street.github.io/docs/software/ungap_the_map/user_guide.html#predict-impact) tool, I'm trying to understand the large-scale impact of a new LTN scheme. Put simply, use a travel demand model and pathfinding on the unedited map to predict vehicle counts along every road. Then repeat the same with the new filters, and look at the difference in vehicle counts along each road. This should predict the short-term effect of the LTN -- where drivers will try to detour, which major (or minor -- who knows) roads will get busier. It'll also show unexpected effects elsewhere.
A key requirement for this to be useful is accurate OD data for driving trips. Lots of ideas about this, but for now, assuming it as input (and using the existing UK flow …
> Predict short-term LTN impact

- Cargo.lock
- game/src/devtools/compare_counts.rs
- game/src/devtools/mod.rs
- game/src/lib.rs
- ltn/Cargo.toml
- ltn/src/impact/compare.rs
- ltn/src/impact/mod.rs
- ltn/src/impact/ui.rs
- ltn/src/lib.rs
- map_gui/src/tools/colors.rs
- map_gui/src/tools/compare_counts.rs
- map_gui/src/tools/mod.rs
- map_model/src/pathfind/v1.rs
#837 started a UI for comparing the total number of trips that cross roads and intersections. The comparison was before/after an LTN change. But that was too limiting -- comparing traffic volumes is actually a pretty general-purpose concern. So much that we've reinvented it a few times in A/B Street -- Ungap the Map's mode shift prediction is _somewhat_ similar. The simulation has a real-time relative throughput layer. There are a few debug UIs to see how many trips will change their path if different pathfinding parameters are tuned. Etc.
And now a new goal has come up -- take real traffic counts from sensor data, and calibrate an existing travel demand model with them. One basic step in that process is comparing predicted traffic volume with real data.
So this PR carves out a serialized …
> Compare traffic counts generically

- Cargo.lock
- abstio/src/abst_paths.rs
- fifteen_min/Cargo.toml
- fifteen_min/src/lib.rs
- ltn/Cargo.toml
- ltn/src/browse.rs
- ltn/src/filters.rs
- ltn/src/lib.rs
- ltn/src/partition.rs
- ltn/src/save.rs
- map_gui/src/lib.rs
- map_gui/src/simple_app.rs
- map_model/src/objects/block.rs
- osm_viewer/Cargo.toml
- osm_viewer/src/lib.rs
- parking_mapper/Cargo.toml
- parking_mapper/src/main.rs
- santa/src/lib.rs
This adds the absolute mvp for file management in the LTN tool. Start fresh, save a proposal, load.
A proposal captures both the modal filters created, and any partitioning changes. The format is completely tied to the current map data and blockfinding code, meaning a user might save a proposal, then try to open it a few weeks later in a new version of the tool, and it'll break. As vague mitigation, capture the version of A/B Street used in the proposal, so we could at least use an older version of the software to load a proposal.
The UX for managing proposals is awful -- no prompting to save before switching maps, no stopping you from overriding an existing file, no uploading, etc. I'm not able to re-use some of edit mode's UI, because it's tied to `MapEdits`. So consider this further …
> Save/load LTN state

- game/src/debug/mod.rs
- map_model/src/objects/block.rs
- tests/goldenfiles/blockfinding.txt
- tests/src/main.rs
too far, by not trying to trace near railways or cycle-only
bridges/tunnels. This is an imperfect heuristic, but it makes
significant progress in most maps.
#848 has some of the story. The colored polygons should represent the area bounded by major roads, which is a first approximation of a "neighborhood."
Now for the juicy comparisons!
Tempe before:
After:
Bristol before:
After:
Camden before (CC @georgio8 -- still many problems here, but slowly getting better):
After:
Southwark before:
After:
Some regressions near Burgess park, but improvements elsewhere
And Levenshulme becomes almost entirely correct. Before:
After:
> Prevent many cases of blocks with overlapping geometry or that extend

- ltn/src/browse.rs
- ltn/src/connectivity.rs
- ltn/src/lib.rs
background and water/parks, but before everything else. It's much easier
to understand the actual basemap this way -- you can see roads clearly.
TODO: Arrows in connectivity mode are covered up
TODO: drawing cells as streets now breaks
Before:
After:
The basemap color scheme and the colors for neighborhoods and cells **really** need tuning
> In the LTN browse and connectivity tool, draw the areas after the map

- cli/src/import_grid2demand.rs
- cli/src/import_scenario.rs
- game/src/sandbox/gameplay/freeform/importers.rs
- importer/src/soundcast/trips.rs
- importer/src/uk.rs
- popdat/src/lib.rs
- popdat/src/od.rs
- sim/src/make/generator.rs
- synthpop/src/counts.rs
- synthpop/src/scenario.rs
or end off-map.
When comparing the predicted traffic volumes around Manchester to real sensor data, the A/B Street predictions are under 1/10th the actual. I want to generate somewhat more reasonable baseline travel demand (at least for home<->work<->home trips) from the 2011 UK desire lines.
The pipeline (which was hacked together in a day for Actdev and not touched since) currently only looks for zones that partly or fully overlap the map's boundary. Hence the problem -- if someone lives or works off-map, they're not represented. So this PR aims to fix that. But also handle pass-through trips, which are tougher...
Say we have a small study area, but we've got a desire line from the red zone to the aqua zone. If we decide that trip interacts with our study area somehow, we need to decide …
> Revive the UK desire line -> scenario pipeline. Include trips that start

- apps/game/src/edit/roads.rs
- data/MANIFEST.json
- geom/src/polyline.rs
- map_gui/src/render/road.rs
- map_model/src/objects/movement.rs
- map_model/src/objects/road.rs
- tests/goldenfiles/prebaked_summaries.json
Before:
After:
This might all be unnecessary if we had a more robust polyline shifting algorithm, but we don't!
> When we can help it, don't shift road polylines twice. #860

- map_model/src/objects/lane.rs
- tests/goldenfiles/blockfinding.txt
... I've been trying to get this fixed since the new year (https://github.com/a-b-street/abstreet/tree/ltn_no_sidewalks). Blockfinding currently gets confused when a road doesn't have a sidewalk on one side. I previously tried to solve this by starting the process from both sides of every road, but then it's unclear how to detect both the side of the road we're starting on and the direction we're facing. The furthest I got (https://github.com/a-b-street/abstreet/tree/ltn_sidewalks_v3) tried to start from any direction, then force the result to always be clockwise. I failed to get that working either by calculating winding numbers -- because there are so many partly self-intersecting polygons everywhere -- or by dealing with it only when merging blocks. All of that went nowhere.
... But …
> Trace blocks starting from roads without sidewalks on both sides

- Cargo.lock
- apps/game/src/challenges/prebake.rs
- apps/map_editor/src/model.rs
- convert_osm/src/extract.rs
- data/MANIFEST.json
- map_model/src/pathfind/mod.rs
- raw_map/Cargo.toml
- raw_map/src/initial.rs
- raw_map/src/lib.rs
- raw_map/src/transform/mod.rs
- raw_map/src/transform/shrink_roads.rs
- tests/goldenfiles/blockfinding.txt
- tests/goldenfiles/prebaked_summaries.json
half. Only rolled out to one map to start.
How can we deal with situations like this:
where thickened roads smush into each other. This is near https://www.openstreetmap.org/node/53179301, and the root problem is bad guesses for the width of the road, or the center-line of each piece of the road not really being the thing that's mapped in OSM.
Let's just apply a very blunt hammer and shrink both roads in half:
A 1.2 meter lane for cars is absurd, of course, but I'm going to vote that this is better than the smushed geometry and all of the other problems that come with it.
Only rolling out to one map for now; this is in service of fixing blockfinding and needing to see what's even happening near here. Much more testing needed before wider rollout
> Find thick dual carriageway roads that overlap, and cut their width in

- apps/ltn/src/browse.rs
- apps/ltn/src/connectivity.rs
- apps/ltn/src/impact/ui.rs
- apps/ltn/src/pathfinding.rs
- apps/ltn/src/per_neighborhood.rs
- apps/ltn/src/save.rs
- apps/ltn/src/select_boundary.rs
Previously the route planning tool was tied to one neighborhood at a time, but this makes little sense. The purpose is to show how someone's driving route may change due to new filters, which could be _anywhere_. So this PR moves the tool to be map-wide. I also rearranged all the panels to try to show common functions better and to de-emphasize experimental/advanced features.
The interior of all neighborhoods is greyed out, and only perimeter roads are shown normally. The intention is to show when a route cuts through any neighborhood, vs stays on perimeter roads. Could still use more styling for this.
> Move the LTN plan route tool

- apps/game/src/info/lane.rs
- map_model/src/objects/block.rs
- tests/goldenfiles/blockfinding.txt
current mix of clockwise and counter-clockwise blocks don't combine.
This appears to fix the neighborhood that couldn't expanded by @XaranDeBruregor in #857:
https://user-images.githubusercontent.com/1664407/158590846-25b7995c-1589-437b-bcb2-051cd9371725.mp4
And the default neighborhoods shown look way better. Bradford before:
After:
The tests show **way** less failures to merge blocks. But Leeds (my main test map!) has a regression that means adjusting blocks will be slower there. I'll probably dig into that one next...
> When merging blocks, try reversing the order of one. Otherwise, the

- map_gui/src/colors.rs
Buildings (and parking lots) are currently a fixed color, which kind of wreaks havoc when drawing LTN neighborhoods or cells as areas. Especially in dense places like Lyon, you can barely see the area beneath. Duncan Geere offered the idea a while back to shade the buildings the same as the color beneath (https://twitter.com/duncangeere/status/1488197326405578771) and I had a few attempts at implementing this. But it was complex and slow, especially for buildings along perimeter roads or that happened to straddle two areas.
This PR is me remembering that color blending exists and doing the simple thing that should've been obvious weeks ago! The results look close to Cindy's designs on Figma -- I'll be adjusting the area color schemes next.
Before:
After:
> De-emphasize buildings in LTN mode

- apps/game/src/lib.rs
- apps/game/src/sandbox/gameplay/play_scenario.rs
- convert_osm/src/gtfs.rs
- data/MANIFEST.json
- importer/src/map_config.rs
- importer/src/utils.rs
- map_model/src/make/transit.rs
- map_model/src/pathfind/v2.rs
- sim/src/mechanics/car.rs
- sim/src/transit.rs
#372 
I really wanted this to be simple, but it turned into some ridiculous yak-shaving to stop the simulation from crashing on the imported routes. I uncovered various bugs with the buses suddenly warping positions, because of the paths between consecutive stops not being built properly. I fixed most (not all) of them. Running the simulation in the city center of SP will crash because of the unfixed one, but Aricanduva and São Miguel Paulista run. No guarantees about the quality of the imported routes; there are likely tons of bugs, but I need to push through this first big change to make smaller progress.
> Start importing GTFS for São Paulo

- apps/ltn/src/filters/mod.rs
- widgetry/src/mapspace/unzoomed.rs
when very unzoomed
Before: When we're at a medium zoom level, regular modal filters are drawn as a "no entry" side -- white line in a red circle. But when we zoom really far out, the symbology switches to a white circle inside a red circle:
https://user-images.githubusercontent.com/1664407/163001345-483d0a21-b721-442a-a4b4-f03b7b0a90e3.mp4
This PR aims for more consistency. When zooming out, we keep drawing a white line in a red circle. The circle is always the same size on the screen -- otherwise spotting filters from really far away would be impossible. The white line inside adjusts to look the same as when more zoomed in.
https://user-images.githubusercontent.com/1664407/163001579-5b19ae89-0bc2-4709-a74c-3a59b91165ec.mp4
This was an idea by @dingaaling. I think it looks much nicer to …
> Always draw unzoomed LTN filters as a red circle with a white line, even

- apps/game/src/info/trip.rs
- apps/game/src/layer/problems.rs
- apps/game/src/sandbox/dashboards/risks.rs
- apps/game/src/sandbox/dashboards/trip_problems.rs
- data/MANIFEST.json
- sim/src/analytics.rs
- sim/src/mechanics/walking.rs
- tests/goldenfiles/prebaked_summaries.json
The original idea in #859 was to emit overcrowding events when people are clumped into crowds, and maybe to slow them down. This PR starts with a simpler idea. Based on the people per square meter on an entire sidewalk segment when someone enters, we emit an overcrowding event and slow them down.
The widened pavement means people experience much less crowding. Some people happen to wind up on other sidewalks at different times and actually experience more crowding -- in other words, fixing one area can move a bottleneck. And there's a feedback loop -- now people spend longer on crowded sidewalks, which makes the crowding last longer. I think this is all realistic.
CC @Robinlovelace, @lucasccdias, and @ChristinaLast (if you're interested in pedestrian modelling in A/B Street, I'm going to …
> Slow down pedestrians when they're on a crowded sidewalk. #859

- .github/workflows/main.yml
- release/build.sh
This helps to address https://github.com/a-b-street/abstreet/issues/107 by adding code signing and notarization to the build process. 
After getting this set up, people on macos will be able to download your releases and run them from the CLI without seeing any warnings.
Some example binaries are available here on my fork: 
https://github.com/michaelkirk/abstreet/actions/runs/2205150116
You should temper your expectations though - ultimately, I think people want to double click on the executable to launch it. For whatever reason, even when signed and notarized themselves, executables outside of a signed .app/.dmg will trigger a warning when launched by double clicking. I think the end goal should ultimately be to package the executables within an .app(s) container, then users would get …
> codesign and notarize macos builds

- apps/game/src/edit/crosswalks.rs
- apps/game/src/edit/mod.rs
- apps/game/src/edit/stop_signs.rs
- apps/game/src/edit/traffic_signals/mod.rs
- apps/game/src/sandbox/gameplay/mod.rs
- map_gui/src/render/intersection.rs
- map_model/src/edits/mod.rs
- map_model/src/edits/perma.rs
- map_model/src/map.rs
- map_model/src/objects/movement.rs
- map_model/src/objects/traffic_signals.rs
- map_model/src/objects/turn.rs
https://user-images.githubusercontent.com/1664407/165338476-10b8bdd7-7298-4846-9c98-628c8c4c64a2.mp4
The UI could certainly do with some work, but it works -- you can now toggle a crosswalk between marked (pedestrians will have priority) and unmarked (pedestrians can still cross, but should yield to vehicles... once more simulation bugs are fixed).
This unblocks #517. @hungerburg may be interested for #795 -- even if the OSM snapping is wrong, you could fix things up with local map edits.
> Let the user make edits to switch between marked/unmarked crosswalks!

- kml/src/lib.rs
Hello, my name is Ilias, I am working on a project using abstreet with Orestis Malaspinas and Thomas Dagier. We found a bug while trying to import kml files. The files that we were trying to use had a leading whitespace in the coordinates nodes which returns an error and crashes the game. Simple fix was to trim the string before splitting it.
> Fixed kml loading by removing leading and trailing whitespaces in coordinates nodes

- apps/game/src/layer/mod.rs
- apps/game/src/layer/problems.rs
- apps/game/src/layer/problems_diff.rs
- sim/src/analytics.rs
- widgetry/src/widgets/mod.rs
- widgetry/src/widgets/panel.rs
This places each agent's experience of a problem at a single point -- the midpoint of the sidewalk for the overcrowding case -- and then draws a small rectangular patch there. For each point, we compare the total number of problems happening there before/after.
The results are quite weird (likely still simulation bugs) and the dataviz is quite poor (hard to see the rectangles), but this is a start. @Robinlovelace, @lucasccdias, @fred-r-ramos -- happen to know any nice dataviz examples to show this kind of information -- a positive or negative count at a location? We could also try to make a heatmap like this, but with both a red and green scale for better/worse:
but maybe the "diffusion" is meaningless here. The problem occurs along an entire road, so we could also just highlight per …
> Create a layer to show where problems are occurring more or less. #859

- apps/game/src/challenges/prebake.rs
- sim/src/lib.rs
- sim/src/mechanics/intersection.rs
- tests/goldenfiles/prebaked_summaries.json
limiting how long a crowd can enter a crosswalk. #517
Before:
https://user-images.githubusercontent.com/1664407/166153561-fca72667-cd03-4403-9353-ab58742733fa.mp4
Every time a pedestrian reaches a stop sign, a car hasn't started a conflicting turn, so they continue. This only happens for pedestrians, because they don't have any concept of getting stuck in an intersection.
After:
https://user-images.githubusercontent.com/1664407/166153607-dd092aba-e657-48de-9019-29ddad3ea2d7.mp4
The ordering between cars and pedestrians with marked/unmarked crosswalks and stop signs / lack of stop signs is still quite wrong, but cars have an upper bound on how long they wait now. In SMP, the overall simulation pretty much unbreaks:
@mdejean, the more I think about your idea for pedestrians joining a queue …
> Prevent pedestrians from endlessly cutting off cars at a stop sign by

- apps/game/src/info/intersection.rs
- apps/game/src/info/lane.rs
- apps/game/src/info/mod.rs
- sim/src/analytics.rs
Lots of the problem / risk exposure analytics have been focused on the person experiencing the problems. But now that we have layers showing **where** problems happen, it's useful to narrow down **when**. So per lane and intersection, there's a new info panel tab wiring up timeseries plots, with all of the filtering and A/B testing available for throughput and delay.
https://user-images.githubusercontent.com/1664407/167253468-794477c7-1020-4b58-a4f0-35c3c8ec5a9a.mp4
The problems aren't stored in `Analytics` in a form optimized for this kind of plotting, but as usual, at the scales of simulations we're looking at right now, the brute-force thing works fine to start with. Thanks cache locality!
> Plot problems over time

- apps/map_editor/src/app.rs
- apps/map_editor/src/edit.rs
- apps/map_editor/src/model.rs
- convert_osm/src/extract.rs
- convert_osm/src/split_ways.rs
- data/MANIFEST.json
- map_model/src/make/mod.rs
- raw_map/src/geometry/geojson.rs
- raw_map/src/initial.rs
- raw_map/src/lib.rs
- raw_map/src/transform/find_short_roads.rs
- raw_map/src/transform/merge_short_road.rs
- raw_map/src/transform/shrink_roads.rs
- raw_map/src/transform/snappy.rs
This moves towards https://github.com/a-b-street/osm2streets/issues/2, and partly addresses https://github.com/a-b-street/osm2streets/issues/11. The next step is to directly store a `PolyLine`, which will make working on `RawMaps` way less tedious and confusing. CC @BudgieInWA
> Make untrimmed_road_geometry infalliable

- apps/game/src/common/mod.rs
- apps/game/src/sandbox/mod.rs
sync, and add a keybinding to synchronize time.
https://user-images.githubusercontent.com/1664407/167659288-da967c06-d824-4512-8a3f-954f5727f0c4.mp4
Command to get here is a bit gnarly: `cargo run --release -- --dev ../../data/system/br/sao_paulo/scenarios/sao_miguel_paulista/Full.bin --edits=smp_sidewalk_widening --diff=../../data/system/br/sao_paulo/maps/sao_miguel_paulista.bin`
But this is reviving a very old UI mode... for direct A/B testing. When a second map is loaded (this example without edits), now loading a scenario in one will load it in the other. And I added a hotkey (control+A) to catch up the secondary sim with the primary. So in practice, this is a very convenient way to watch two simulations side-by-side. In the video above, by 6am, the main noticeable difference is …
> When a secondary map is loaded for debugging, keep the scenarios in

- apps/ltn/src/browse.rs
- apps/ltn/src/common/mod.rs
- apps/ltn/src/connectivity.rs
- apps/ltn/src/save/mod.rs
Everything @dingaaling mentioned
Note:
- I took away the outline style for "Export to geojson" to de-emphasize it. It's very much an advanced bit for GIS people. Iff someone knows what geojson is, they'll know what this button does and what to do with the file
- I split the new/load/save buttons to a new line, because otherwise the left bar gets too wide with "LTN Policy Proposals"
> A number of small UX changes to the LTN tool

- apps/ltn/src/colors.rs
- apps/ltn/src/draw_cells.rs
- apps/ltn/src/neighborhood.rs
- map_model/src/objects/block.rs
- tests/goldenfiles/blockfinding.txt
- tests/goldenfiles/bus_routes/br_sao_paulo_aricanduva.txt
blockfinding. Stop using them as parts of block boundaries, and stop
drawing special "car-free" cells around them.
Motivation in the PR description.
The previous special green cells were particularly noisy in Bristol:
Note the misleading green entrance arrows at the bottom for a tiny piece of segregated cycle path. I don't think seeing the area around snippets of car-free path really added any value. With this PR, it's cleaned up:
Another example before:
and after:
I think it's more clear now when the green roads cross cells. It simultaneously shows that the area is split for drivers, while being still linked together for cyclists and pedestrians. It was harder to see when there were green cells in there too.
CC @dingaaling and also @Robinlovelace, who I recall originally helped with the …
> Change how non-driveable roads (cycleways) work in the LTN tool and

- apps/ltn/src/browse.rs
- apps/ltn/src/components/about.rs
- apps/ltn/src/components/top_panel.rs
- apps/ltn/src/connectivity.rs
- apps/ltn/src/impact/ui.rs
- apps/ltn/src/lib.rs
- apps/ltn/src/partition.rs
- apps/ltn/src/per_neighborhood.rs
- apps/ltn/src/route_planner.rs
- widgetry/src/widgets/mod.rs
- starts in a fixed neighborhood
- hides many controls
- lets users jump to route planning from the per-neighborhood screens
The demo is kind of underwhelming - it's just the LTN tool, but with less stuff!
https://user-images.githubusercontent.com/1664407/168845651-49a830f7-664d-4d76-82b0-412482fe0b2e.mp4
> Start a simplified consultation mode for the LTN tool

- Cargo.lock
- widgetry/Cargo.toml
- widgetry/README.md
- widgetry/src/screen_geom.rs
- widgetry/src/widgets/mod.rs
- widgetry/src/widgets/panel.rs
- Migrated from `stretch 0.3.2` to `taffy 0.1.0`.
- Updated references (code + docs) to taffy.
- Taffy's new_node uses &[Node], instead of Vec<Node> for its children argument.
- Set the doc reference to Taffy with a hyperlink to their [github repo](https://github.com/DioxusLabs/taffy/), instead of their [github page](https://dioxuslabs.github.io/taffy/) since it's still referred to as Stretch there.
- Manually tested by `cargo run`-ing the `widgets_demo` and some of the street demos/games.
**Extra/Side Notes**
- When updating to taffy future (minor) versions, there'll be some breaking changes.
- ex. `taffy.new_node()` will be `taffy.new_with_children()`. [change here](https://github.com/DioxusLabs/taffy/commit/d960ac1c6a624f07801bb25787dd5111aebfb88f)
- and probably some other changes. …
> Migrate from Stretch to Taffy

- apps/game/src/sandbox/speed.rs
- data/MANIFEST.json
- geom/src/polygon.rs
- tests/goldenfiles/prebaked_summaries.json
In the interests of making the `geom` crate simpler and eventually splitting it into a separate repo for https://github.com/a-b-street/osm2streets/issues/3, this PR cleans up the polygon implementation in two ways:
1) Removes old extra implementations of `geom::Polygon -> geo::Polygon`
2) Uses georust for `contains_pt`
I'm regenerating everything in A/B Street now to double-check there are no unexpected behavioral changes
CC @michaelkirk as FYI
> More directly use georust for polygons

- Cargo.lock
- Cargo.toml
corresponding: https://github.com/urschrei/polylabel-rs/pull/24
It's also fine if you want to leave in the duplicated dependency for now - I just thought I'd upstream this since I was testing something locally that required de-duping.
> use unreleased polylabel to avoid duplicated geo dep

- apps/ltn/src/filters/existing.rs
- convert_osm/src/extract.rs
- convert_osm/src/lib.rs
- convert_osm/src/split_ways.rs
- data/MANIFEST.json
- importer/src/map_config.rs
- map_model/src/make/mod.rs
- map_model/src/objects/road.rs
- raw_map/src/lib.rs
A few unrelated things grouped together so I only have to regenerate everything once:
1) Disable elevation import almost everywhere, since it slows down import and has bad results.
2) Import schools tagged a certain way in OSM
3) Import modal filters tagged as nodes in OSM
> Batched map importing changes

- geom/src/bounds.rs
- geom/src/polygon.rs
- map_gui/src/tools/labels.rs
- widgetry/src/geom/mod.rs
modifying polygons in-place and batching the transformations.
This is a followup to @michaelkirk's idea in #740. Some efficient in-place way to batch together transformations would be cool, but in practice, this is the one case that's a noticeable perf impact. So I think the one-off code is well worth it.
I measured the improvement to be about 35%. One zoom level on a large map dropped from 0.4s to 0.26s.
> Improve the performance of rendering road labels for a zoom level by

- widgetry/src/event.rs
For me (Linux Xorg + firefox) and at least one other critical user (I think Mac or Windows, web browser), the canvas scroll speed is way too intense:
https://user-images.githubusercontent.com/1664407/179973998-68e150e0-5753-4df4-83b6-886e18958dfd.mp4
Each zoom step is a single gentle flick of a mouse scroll wheel or laptop touchpad. With this PR, the zoom speed feels much better:
https://user-images.githubusercontent.com/1664407/179974286-9083a113-807e-4980-8d71-9be80be074c1.mp4
The previous `0.1` factor was introduced in #310. #95 has additional context (but it was about the scroll speed for menus, not the canvas). I'm short on time at the moment and going to merge this for a release, but I'll do more reading and look for a robust platform-independent solution. CC @michaelkirk as FYI.
We …
> Reduce the scroll speed on web

- Cargo.lock
- apps/ltn/Cargo.toml
- apps/ltn/src/browse.rs
- apps/ltn/src/edit/one_ways.rs
- apps/ltn/src/edit/shortcuts.rs
- apps/ltn/src/filters/existing.rs
- apps/ltn/src/impact/mod.rs
- apps/ltn/src/impact/ui.rs
- apps/ltn/src/lib.rs
- apps/ltn/src/route_planner.rs
- apps/ltn/src/shortcuts.rs
- map_gui/src/tools/draw_overlapping_paths.rs
- map_model/src/pathfind/pathfinder.rs
- map_model/src/pathfind/v2.rs
- sim/src/lib.rs
- sim/src/make/mod.rs
- sim/src/sim/scenario.rs
- synthpop/src/lib.rs
- synthpop/src/make/activity_model.rs
- synthpop/src/make/generator.rs
- synthpop/src/make/mod.rs
- widgetry/src/backend_glow.rs
For @darthvarad. This is the semi-abandoned mode in the LTN tool for estimating overall traffic increases/decreases along every road in the map, using a travel demand model.
Lots of changes to get it to a usable state:
- make it work for every single map. In Seattle and GB, we have better demand models, which're still used. Everywhere else, fallback to the dynamically generated proletariat robot "home to work" model.
- Enhance the UI for showing exact paths that differ before/after changes
- Possibly fix some of the "spurious pathfinding change" bug (#868). I added support for bollards defined just as nodes in OSM a while back, but didn't realize it affects the road they're on -- the map's built-in pathfinder would allow cars through.
- Add a new CSV export of the before/after counts …
> Overhaul the LTN tool's impact prediction

- apps/ltn/src/colors.rs
- apps/ltn/src/connectivity.rs
- apps/ltn/src/draw_cells.rs
- apps/ltn/src/lib.rs
default again!
https://user-images.githubusercontent.com/1664407/183445585-f5b21685-a499-4661-96d8-c1379b24f1d0.mp4
@mfbenitezp generously helped figure out how to improve the LTN design, so now we have this huge improvement! We used a qualitative color palette from colorbrewer, skipping some values too close to red or grey. Then lots of tuning to make the division between areas obvious, but not overwhelming.
> Improve the colors used for LTN cells as areas, and make that the

- abstutil/src/serde.rs
- apps/game/src/sandbox/dashboards/trip_table.rs
- geom/src/lib.rs
- geom/src/polygon.rs
- geom/src/stats.rs
- geom/src/tessellation.rs
- map_gui/src/render/map.rs
- map_model/src/objects/intersection.rs
- widgetry/src/backend_glow.rs
- widgetry/src/geom/mod.rs
- widgetry/src/svg.rs
- widgetry/src/widgets/fan_chart.rs
- widgetry/src/widgets/plots.rs
I adapted the idea in your branch and started this transition. This nearly rids us of polygons that don't have valid outer/inner rings.
I think the next steps are now:
1) Look at the last two `Polygon::precomputed` callers -- circles and polylines. They send in valid rings. There might be a perf impact to using earcutr. So maybe `geom::Polygon` optionally stores some indices sometimes. The approach in your branch was to change the API to put out a `Tessellation` instead of a `Polygon`, but this will affect **lots** of code, and I'm not sure it's what we want. A `Polygon` is "stronger" than a `Tessellation`.
2) Be more careful about converting `geo::Polygon` to `geom::Polygon`. The current `From` implementation can crash -- and does, in a few maps that intersect OSM areas with the boundary …
> Create Tessellation and switch some callers to it

- apps/game/src/debug/blockfinder.rs
- apps/ltn/src/partition.rs
- map_model/src/objects/block.rs
- tests/goldenfiles/blockfinding.txt
- tests/src/main.rs
draw more LTN boundaries. #857
These diffs are a bit hard to see because all of the colors jump, but before:
after:
and before:
after:
The real proof of improvement is being able to define an LTN boundary in Islington that wasn't working before:
> Detect and merge "holes" when blockfinding. This makes it possible to

- apps/ltn/src/browse.rs
- apps/ltn/src/components/layers.rs
- apps/ltn/src/components/mod.rs
- apps/ltn/src/connectivity.rs
- apps/ltn/src/edit/mod.rs
- apps/ltn/src/impact/ui.rs
- apps/ltn/src/lib.rs
- apps/ltn/src/route_planner.rs
- apps/ltn/src/select_boundary.rs
- map_gui/src/tools/compare_counts.rs
- widgetry/src/tools/colors.rs
1) Zoom buttons. Some users haven't figured out how to use the scroll wheel or trackpad to zoom. Use the zoom buttons from Ungap.
2) Add a per-mode collapsible legend, also from Ungap. Not everything is explained there yet, and maybe it needs tooltips / popups with more info, but this is a start.
The collapsible legend also carves out a spot for toggleable layers. Maybe showing existing cycling facilities, other POIs, bus routes could happen in the future.
https://user-images.githubusercontent.com/1664407/185933145-e5a4c6c4-19a4-4b54-9a30-7517b678e25b.mp4
> LTN zoom/legend

- apps/ltn/src/browse.rs
- apps/ltn/src/colors.rs
- apps/ltn/src/components/layers.rs
- apps/ltn/src/connectivity.rs
- apps/ltn/src/edit/mod.rs
- apps/ltn/src/filters/existing.rs
- apps/ltn/src/impact/ui.rs
- apps/ltn/src/lib.rs
- apps/ltn/src/route_planner.rs
- apps/ltn/src/select_boundary.rs
- convert_osm/src/extract.rs
- convert_osm/src/lib.rs
- data/MANIFEST.json
- map_model/src/lib.rs
- map_model/src/make/mod.rs
- map_model/src/map.rs
- raw_map/src/lib.rs
#965 
https://user-images.githubusercontent.com/1664407/186162220-dab2472d-e218-4a50-983c-68a94a8405f4.mp4
When might you need a bus gate instead of a physical filter? This PR looks for roads with bus routes on them according to OSM route relations. That detection is imperfect (in the presence of some osm2streets transformations), but it's good enough for now.
The new legend widget now has its first toggleable layer to show things. Next up, possibly a pop-up asking the user if they want a bus gate if they try to filter a road with a route.
I need to regenerate all maps with this change, leaving the PR open until that's done
> Show bus routes in the LTN tool

- apps/ltn/src/components/layers.rs
- apps/ltn/src/connectivity.rs
- apps/ltn/src/edit/filters.rs
- apps/ltn/src/edit/mod.rs
- apps/ltn/src/edit/one_ways.rs
- apps/ltn/src/edit/shortcuts.rs
- apps/ltn/src/filters/mod.rs
- apps/ltn/src/lib.rs
- apps/ltn/src/neighbourhood.rs
- apps/ltn/src/shortcuts.rs
- data/system/assets/map/private_road.svg
#968 
This looks for roads tagged `access=no` or `access=private` and treats the road as non-driveable for the purposes of calculating cells and shortcuts.
Before, Pentonville prison has loads of shortcuts going through:
After, none:
But I have 3 concerns / open questions before proceeding with this.
1) Should you be able to put a new filter on a private road? Since no shortcuts go through them, most users won't try to, but I'm not sure what to do here. And should we popup an error explaining that it's private, or just make it not hoverable/selectable at all?
2) How should we render / indicate the private roads? Seems like it's a relevant thing to communicate in the tool.
3) This PR results in a warning in Islington, because a private estate is now a disconnected cell:
The analysis is …
> Deal with roads in the LTN tool marked access=no,private

- apps/ltn/src/edit/filters.rs
- apps/ltn/src/edit/freehand_filters.rs
- apps/ltn/src/edit/mod.rs
- apps/ltn/src/edit/one_ways.rs
Previously: you try to filter a one-way street and get an error. From user interviews, most people then switch tools, click the road twice to make it two-way, then go back and add a filter. Very clunky UX. #965 
So let's just ask the user what they want to do:
https://user-images.githubusercontent.com/1664407/186913322-e7bfa357-64f6-4a92-8180-8c2d60ba7567.mp4
This also works in the freehand tool
> Let people change one-way streets to two-way and add a filter

- data/MANIFEST.json
- map_model/src/pathfind/vehicles.rs
uber-turn! Fixed #978
Before:
After:
I still need to:
1) Validate everything in the LTN tool is sane -- shortcuts and route planning (near old and new filters)
2) Figure out if this could've possibly affected the contraction hierarchies in maps. If so, need to regenerate everything. Happy Friday!
> If a single road can't be crossed in an uber-turn, don't allow the

- apps/game/src/edit/roads.rs
- apps/game/src/edit/traffic_signals/mod.rs
- apps/game/src/layer/traffic.rs
- apps/game/src/sandbox/dashboards/commuter.rs
- apps/ltn/src/draw_cells.rs
- apps/parking_mapper/src/mapper.rs
- convert_osm/src/lib.rs
- data/MANIFEST.json
- geom/src/polygon.rs
- geom/src/ring.rs
- geom/src/tessellation.rs
- map_model/src/objects/block.rs
- popdat/src/od.rs
Towards the quest of making `geom::Polygon` always internally just wrap a `geo::Polygon`.
`geom` tries to be stricter than `geo`, rejecting "bad" geometry upfront to try to isolate a problem at its source. A `Ring` must not have any duplicate points (adjacent or not), except for the first = last point. This is further complicated by "duplicate" points being defined a bit strictly. Every `Pt2D` [trims its f64's down to a few decimal places](https://github.com/a-b-street/abstreet/blob/0e890a68cd7fc6a7be78e919a2587b89ac36a860/geom/src/lib.rs#L48).
I'm starting to question if this attempt at upfront strictness is even helpful. In the beginning, it was an attempt to "clean up" a bunch of crazy OSM geometry I was encountering or algorithmically producing, but I've lost context on many of the …
> Make the conversion from geo::Polygon to geom::Polygon fallible

- map_gui/src/tools/labels.rs
- widgetry/src/text.rs
This is a followup to #962 related to #173. Before:
After:
More dramatically, before:
after:
Thanks to @jamesneb for working on curvy road labels before in #917, to @Zireael07 for references about how other projects do this, and [Twitter people](https://twitter.com/CarlinoDustin/status/1564973268624343047) for more ideas
The code has some comments. Basically:
1) We try to draw a label for every road segment
2) First render the road name normally (with some arbitrary font size), calculate the width and height needed
3) Figure out how much to scale the text to fit the road segment polygon. The text height is bounded by the road's width, minus a buffer for the outline of the road. The text width is bounded by the road's length.
4) Then use SVG `textPath` to draw the text along the curve of …
> Make road labels fit in the road

- apps/game/src/info/intersection.rs
- apps/game/src/layer/elevation.rs
- apps/game/src/sandbox/speed.rs
- apps/ltn/src/draw_cells.rs
- geom/src/polygon.rs
- map_gui/src/tools/city_picker.rs
- map_gui/src/tools/heatmap.rs
With this PR, every `Polygon` consists of valid `Rings`! That means the true cleanup can happen next:
- simplifying `Polygon`'s API. Things like `to_outline` are now guaranteed to succeed!
- changing the internal representation to not store the tessellation
> Every Polygon is valid

- apps/game/src/debug/blockfinder.rs
- apps/game/src/debug/mod.rs
- apps/game/src/devtools/story.rs
- apps/game/src/edit/multiple_roads.rs
- apps/game/src/info/intersection.rs
- apps/game/src/layer/elevation.rs
- apps/game/src/layer/traffic.rs
- apps/game/src/sandbox/dashboards/commuter.rs
- apps/game/src/sandbox/dashboards/traffic_signals.rs
- apps/game/src/sandbox/dashboards/travel_times.rs
- apps/ltn/src/connectivity.rs
- apps/ltn/src/customize_boundary.rs
- apps/ltn/src/draw_cells.rs
- apps/ltn/src/edit/shortcuts.rs
- geom/src/polygon.rs
- map_gui/src/render/building.rs
- map_gui/src/render/intersection.rs
- map_gui/src/render/lane.rs
- map_gui/src/render/parking_lot.rs
- map_gui/src/render/traffic_signal.rs
- map_gui/src/render/turn.rs
- map_gui/src/tools/city_picker.rs
- map_model/src/objects/block.rs
- widgetry/src/mapspace/world.rs
- widgetry/src/widgets/dropdown.rs
- widgetry/src/widgets/mod.rs
- widgetry/src/widgets/spinner.rs
- widgetry/src/widgets/text_box.rs
We're almost at the point of changing `Polygon` to just store `Vec<Ring>`. Before making that big rip, I want to fix up some of the methods on `Polygon` and their callers. This PR just does a little of that.
Shouldn't be any behavioral changes, except maybe for some slight performance loss from cloning. That'll go away once the implementation is cutover completely.
> Simplify Polygon API, now that we always have Rings

- apps/ltn/src/lib.rs
- apps/ltn/src/route_planner.rs
Probably this will be a commonly used mode of the tool, but the UI needs so much work. This makes a few simple improvements:
1) don't show extra panel stuff when the user hasn't even specified the waypoints yet
2) don't show walking/cycling route by default. 4 routes (and colors) is overwhelming. 2 is less bad.
3) slightly improve performance of dragging waypoints. 0.05s down to 0.03s in one benchmark.
https://user-images.githubusercontent.com/1664407/188423733-674eec08-6a28-4e24-905e-765feb4db3a4.mp4
> Improve LTN route planner UI

- Cargo.lock
- Cargo.toml
- apps/game/src/layer/elevation.rs
- apps/ltn/src/draw_cells.rs
- map_gui/src/tools/heatmap.rs
No change in behavior here for abstreet, I just go tired of having to update contour every time there was a geojson release.
> Update contour, which no longer depends on geojson crate

- apps/ltn/src/app.rs
- apps/ltn/src/components/appwide_panel.rs
- apps/ltn/src/customize_boundary.rs
- apps/ltn/src/design_ltn.rs
- apps/ltn/src/edit/filters.rs
- apps/ltn/src/edit/freehand_filters.rs
- apps/ltn/src/edit/mod.rs
- apps/ltn/src/edit/one_ways.rs
- apps/ltn/src/export.rs
- apps/ltn/src/filters/auto.rs
- apps/ltn/src/filters/existing.rs
- apps/ltn/src/filters/mod.rs
- apps/ltn/src/impact/mod.rs
- apps/ltn/src/impact/ui.rs
- apps/ltn/src/lib.rs
- apps/ltn/src/neighbourhood.rs
- apps/ltn/src/partition.rs
- apps/ltn/src/pick_area.rs
- apps/ltn/src/route_planner.rs
- apps/ltn/src/save/mod.rs
- apps/ltn/src/save/share.rs
- apps/ltn/src/select_boundary.rs
- apps/ltn/src/shortcuts.rs
This is a big new idea for #765. You can have multiple "files" (or proposals) in the LTN tool open at once, and quickly switch between them. When you make any edit to a file, it starts a new "file" pointing out the unsaved changes. When you save, you can choose to overwrite the base file, or save as a new file. This is meant to encourage rapid experimentation and "forking" off different ideas into multiple possibilities. Very open question to see how people actually use this, and if it's useful.
Try it out at http://abstreet.s3-website.us-east-2.amazonaws.com/dev/ltn.html?system/us/seattle/maps/montlake.bin
https://user-images.githubusercontent.com/1664407/194716716-ff00f077-0702-4264-bea5-8097bff28d65.mp4
A number of open questions / UX problems / confusing things:
1) If you load a …
> Make LTN proposal management handle unsaved changes better

- apps/ltn/src/components/appwide_panel.rs
- apps/ltn/src/components/layers.rs
- apps/ltn/src/crossings.rs
- widgetry/src/mapspace/world.rs
A quick idea for https://github.com/a-b-street/osm2streets/issues/99 in the LTN tool. Per road segment, show how long it takes to walk to the nearest crossing.:
This isn't the right thing to show for a few reasons:
- the nearest crossing might be for a different road, aka, go somewhere irrelevant
- the granularity is at the road segment level, so long roads have weird results
but it's a start, and an optional layer
> Visualize how long to walk to the nearest crossing

- apps/game/src/ungap/layers.rs
- data/MANIFEST.json
- importer/src/map_config.rs
Thanks to @mem48, a digital elevation model from Ordnance Survey data is now added to https://github.com/eldang/elevation_lookups/pull/31. I'm reimporting all UK maps now and will update this PR with the pushed data when it's done. #1017, #82
There's a substantial slowdown to importing maps... 10s just for the small east Bristol map (previously just 15s in total), and 93s for all of Central London (previously about 2 minutes total). The parallelism also has to be turned down, because handling the big geotiff takes some RAM. I'd love to get to a pure Rust geotiff reader (to get rid of Docker and the ever-painful GDAL installation problems) and figure out how to use memmap + just reading necessary parts of the raster.
Spot check validation via Ungap the Map:
> Import elevation data for the UK

- apps/fifteen_min/src/bus.rs
- apps/game/src/ungap/trip/mod.rs
- apps/ltn/src/route_planner.rs
- map_gui/src/tools/waypoints.rs
- synthpop/src/endpoint.rs
Before, maps with low coverage of buildings are basically broken in the route tool:
https://user-images.githubusercontent.com/1664407/201434548-e9298a66-2064-4c9d-a36f-93eba0d71658.mp4
Now they work much better (mind the lag):
https://user-images.githubusercontent.com/1664407/201434570-43f6fdd0-b99d-4e6e-a53f-86ac131e6a30.mp4
> Let the route tool start/end at roads, not just buildings

- apps/ltn/src/app.rs
- apps/ltn/src/components/layers.rs
- apps/ltn/src/edit/filters.rs
- apps/ltn/src/edit/freehand_filters.rs
- apps/ltn/src/edit/mod.rs
User studies have shown people get scared off by this screen and often just click Cancel:
And it's an annoying warning to get every single time you filter a one-way or road with a bus route. The app can automatically resolve (by using a bus gate filter, or making the segment two-way first), and we pretty much always want people to carry on with that action. So instead, let's just warn them the very first time it happens (per session) and by default, resolve automatically afterwards:
https://user-images.githubusercontent.com/1664407/201490388-612a89f4-5a54-4bd8-9d66-557d4bfb6a3d.mp4
> Fix bus gates and one-ways automatically

- Cargo.lock
- apps/map_editor/src/app.rs
- apps/map_editor/src/edit.rs
- apps/map_editor/src/lib.rs
- apps/map_editor/src/model.rs
- convert_osm/src/elevation.rs
- convert_osm/src/lib.rs
- convert_osm/src/parking.rs
- data/MANIFEST.json
- map_model/src/make/mod.rs
- map_model/src/map.rs
- tests/goldenfiles/prebaked_summaries.json
- tests/src/main.rs
This changes the RawMap format (increasing size now that derived geometry is stored) and fixes some bus lanes.
The map_editor temporarily regresses in behavior -- intersection geometry isn't constantly recalculated yet.
CC @BudgieInWA for how osm2streets API changes look on the other side. I'll do something about recalculating intersection geometry constantly in the editor later, but it's not important right now. Am regenerating all maps with these changes
> Upgrade osm2streets.

- Cargo.lock
- geom/src/polyline.rs
- geom/src/pt.rs
- geom/src/ring.rs
On a new dev build, compiling fails due to the following error:
```
Compiling geo-types v0.7.7
error: expected `,`, found `.`
--> /home/matthieu/.cargo/registry/src/github.com-1ecc6299db9ec823/geo-types-0.7.7/src/geometry/geometry_collection.rs:111:25
|
111 | #[deprecated(since = 0.7.5, note = "Use `GeometryCollection::from(vec![geom])` instead.")]
|                         ^ expected `,`
```
This issue was [fixed in geo-types 0.7.8](https://github.com/georust/geo/commit/dbe5b4f1264fcf855e9c56096306e1bae65804aa), so I updated it using `cargo update --package geo-types`.
#
Side note: I am looking into contributing to this project over the next few weeks. I'll take a look at those [good first issues](https://github.com/a-b-street/abstreet/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+i …
> Update geo-types to 0.7.8

- map_model/src/lib.rs
I have fixed a broken link for the autogenerated documentation for the map model.
I am not sure what the steps to QA are, but verifying the difference between where the old link brings vs where the new link brings should be good enough to assure its validity in production.
Update:
Created an issue associated to this PR
Closes #1050
> fixing broken link in map model documentation

- apps/ltn/src/app.rs
- apps/ltn/src/components/layers.rs
- apps/ltn/src/components/mod.rs
- apps/ltn/src/logic/partition.rs
- apps/ltn/src/neighbourhood.rs
- apps/ltn/src/pages/crossings.rs
- apps/ltn/src/pages/design_ltn/page.rs
- apps/ltn/src/pages/per_resident_impact.rs
- apps/ltn/src/pages/pick_area.rs
- apps/ltn/src/pages/route_planner.rs
- apps/ltn/src/pages/select_boundary.rs
- apps/ltn/src/render/colors.rs
- apps/ltn/src/render/mod.rs
- map_gui/src/colors.rs
perimeter are a main road, and that's OK -- treat them as interior, let them be filtered, and calculate entrance/exits and shortcuts appropriately.
(A bunch of design changes then happen as a consequence.)
Previously, we often have "incomplete" neighbourhoods, that aren't bounded on all sides by main roads. Part of the boundary is a local road, and that means users can't add filters to those local perimeter roads, and that the calculation of shortcuts is pretty ridiculous:
(Only the southern edge is a main road)
For the lifetime of the LTN tool, I've tried to insist that a neighbourhood is bounded on ALL sides by a main road. Sometimes that can be made true by stretching the neighbourhood boundary much farther to the next main road -- giving something with many cells, most attached to …
> Huge redesign to LTN neighbourhood boundaries! Not all parts of a

- apps/ltn/src/components/appwide_panel.rs
- apps/ltn/src/components/layers.rs
- apps/ltn/src/components/mod.rs
- apps/ltn/src/pages/cycle_network.rs
- apps/ltn/src/pages/mod.rs
- apps/ltn/src/pages/pick_area.rs
- apps/ltn/src/render/colors.rs
- apps/ltn/src/save/mod.rs
I've been trying to find ways of emphasizing the benefits of LTNs, instead of just focusing on explaining impact to concerned drivers. This shows the explicitly built cycle network (lanes, both segregated and not) alongside a "shortcuts everywhere" view. If there's no through-traffic (for motor vehicles) possible on some streets, then they're quite suitable for cycling (and often called neighbourhood greenway, quietway, etc). So in addition to residents on those streets benefiting, it can be a cheap way to expand the effective cycle network.
Plenty of design issues with this view and noted limitations. This is a first step.
Here it is in Seattle. Rat-running is possible pretty much everywhere; the attempted greenway routes there don't really work (in my opinion) partly for this reason. …
> Start a new cycle network page in the LTN tool

- widgetry/src/canvas.rs
- widgetry/src/widgets/panel.rs
winit flipped it's negative/positive convention in 0.27.0
(we updated to that version in a5ff8029574434bd0e6448bdce257757e76cc608)
Consequently, we have to flip our convention as well.
Tested on mac native and mac browser
closes #831  (superseded)
> Fix (reverse) horizontal scrolling.

- apps/ltn/src/render/mod.rs
- map_model/src/map.rs
- tests/src/main.rs
I know this is not the priority, but it's been bugging me 😉 
This is a first attempt to "stack" turn restriction icons along the length of the road when there is more than one. (Mentioned in https://github.com/a-b-street/abstreet/issues/1096). For a long road segment, this works reasonably well.
The problem cases are:
- Where the turn restriction icons occupy more than half the length of the road. Currently, they are forced into the correct half of the road but can still overlap each other.
- Worse, when the road is shorter than it is wide. 
- If the road segment is curved, then this can cause oddities where the turn type is assessed differently depending on how close the icon is to the intersection.
> WIP improvements for placement of turn restriction icons

- .github/workflows/book.yml
The [release process](https://a-b-street.github.io/docs/tech/dev/release.html) has enough overhead that I don't do it often, especially when busy with other work. So start building the LTN tool and deploying to GH pages every single commit.
Demo of the recent 4daf9a89aceef6e072f71992d248a4c5e8099028: https://a-b-street.github.io/abstreet/web/ltn.html?system/il/tel_aviv/maps/center.bin
> Build the LTN app for web in GH actions

- Cargo.lock
- apps/game/src/devtools/kml.rs
- apps/game/src/edit/mod.rs
- apps/game/src/info/building.rs
- apps/osm_viewer/src/viewer.rs
- cli/src/one_step_import.rs
- convert_osm/src/extract.rs
- data/MANIFEST.json
- importer/src/lib.rs
- importer/src/soundcast/popdat.rs
- importer/src/utils.rs
- map_model/src/make/buildings.rs
Now that osm2streets can read XML or PBF files without caring about the difference, the import pipeline here can be slimmed down to use the smaller (and faster tor read) PBF files. The `data/input` directory with all maps shrinks from 42GB to 34GB with this change.
I regenerated everything on a laptop without Docker working properly, so the elevation data seems to have broken for Seattle. Uploading anyway. Working on a much simpler elevation reader without the same dependency problems in https://github.com/a-b-street/abstreet/tree/elevation and unlikely to do a new release anytime soon.
> Switch the import process to use osm.pbf

- Cargo.lock
- apps/game/src/edit/mod.rs
- cloud/worker_script.sh
- convert_osm/Cargo.toml
- convert_osm/src/elevation.rs
- convert_osm/src/lib.rs
- data/MANIFEST.json
- importer/src/map_config.rs
GeoTIFFs. #82
This PR switches from Docker + Python/GDAL-based https://github.com/eldang/elevation_lookups to pure Rust https://github.com/dabreegster/elevation. The benefits are:
- Portability. In the span of a year or two, the Docker + GDAL based environment broke on newer Ubuntu, making it a chore just to re-run. Pure Rust means everything compiles anywhere with no external dependencies.
- Simplicity. The code is just bilinear interpolation on top of https://github.com/pka/georaster/. The simplifying assumption that removes the need for GDAL is that the input is a GeoTIFF in EPSG:4326. `gdalwarp -t_srs EPSG:4326 kc_2016_lidar.tif king_county_2016_lidar.tif` as a one-time step is all it takes to transform the Seattle file, and the UK one was already in the right coordinate system.
- …
> Get elevation data from a pure Rust crate that only handles some

- apps/game/src/common/mod.rs
- apps/game/src/common/warp.rs
- apps/game/src/lib.rs
- Add --layer parameter to start with specific layers (steep_streets, elevation, map_edits, no_sidewalks, transit_network)
- Add --info parameter to open specific info panels using warp syntax (e.g. b42 for building 42)
- Export inner_warp_to_id function for URL parameter handling
- Addresses issue #666
> Add startup flags for layer and info URL parameters
